"""Generate a complete Vite + React + TypeScript + Fluent 2 project from a spec revision.

Deterministic: the same spec revision, design system and generator version give
byte-identical files (no timestamps, sorted keys, stable ordering), so diffs
between revisions show only real changes. Generation is refused while the UI IR
has errors (ADR-0013); warnings (placeholders) are carried into the output as
visible "not supported yet" markers.
"""

from __future__ import annotations

import hashlib
import html
import json
import re
from dataclasses import replace
from importlib import resources
from typing import Any

from pydantic import BaseModel, Field

from appspec import ApplicationSpec
from design_system import (
    BrandTheme,
    DesignSystemContract,
    RenderedScreen,
    UiDocument,
    UiIssue,
    brand_ramp,
    derive_document,
    render_screens,
    validate_document,
)
from design_system.ir import Form as IrForm
from design_system.ir import Table as IrTable
from design_system.ir import walk

from .data import STORE_TS, entities_ts, openapi_json
from .jsx import DataBindings, GenerationError, Printer, components_in, is_library_component, literal, needs_layout

GENERATOR = "codegen-react"
GENERATOR_VERSION = "0.6.0"
MANIFEST = "workspace-manifest.json"


class GenerationBlocked(Exception):
    """The UI IR has errors; code is not generated until they are fixed."""

    def __init__(self, issues: list[UiIssue]) -> None:
        super().__init__(f"{len(issues)} UI error(s) block code generation")
        self.issues = issues


class GeneratedProject(BaseModel):
    generator: str
    spec_revision: int | None
    design_system: str
    files: dict[str, str] = Field(description="Path -> content, in a stable order.")
    warnings: list[UiIssue] = Field(default_factory=list)

    def sha256(self, path: str) -> str:
        return hashlib.sha256(self.files[path].encode("utf-8")).hexdigest()


def toolchain() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(
        resources.files(__package__).joinpath("toolchain.json").read_text(encoding="utf-8")
    )
    return data


def pascal(identifier: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^a-zA-Z0-9]+", identifier) if part)


def package_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:60].strip("-")
    return f"{slug}-app" if slug and slug[0].isalpha() else "generated-app"


def design_system_label(contract: DesignSystemContract, theme: BrandTheme | None) -> str:
    base = f"{contract.id}@{contract.version}"
    return f"{theme.selector} ({base})" if theme is not None else base


def _header(spec_revision: int | None, contract: DesignSystemContract) -> str:
    revision = f"r{spec_revision}" if spec_revision is not None else "an unsaved spec"
    return (
        f"// Generated by {GENERATOR}@{GENERATOR_VERSION} from spec {revision} "
        f"(UI IR v1, design system {contract.id}@{contract.version}).\n"
        "// You may edit this file: upgrading in the workspace merges your edits with the regenerated code.\n"
    )


def _screen_file(screen: RenderedScreen, header: str, contract: DesignSystemContract, bindings: DataBindings) -> str:
    packages = {m.package for m in contract.mappings.values()} - {"html"}
    if len(packages) != 1:
        raise GenerationError("expected exactly one component package in the contract")
    [package] = packages
    printer = Printer(replace(bindings, current_route=screen.route))
    body = printer.nodes(screen.root, 3)
    used = components_in(screen.root) | printer.extra_components
    library = sorted(c for c in used if is_library_component(c))
    has_layout = needs_layout(screen.root)
    lines = [header.rstrip("\n"), ""]
    if library:
        lines.append(f"import {{ {', '.join(library)} }} from {literal(package)};")
    router = sorted(
        name
        for name, used_ in (("useNavigate", printer.uses_navigate), ("useSearchParams", printer.uses_search_params))
        if used_
    )
    if router:
        lines.append(f'import {{ {", ".join(router)} }} from "react-router-dom";')
    if printer.uses_confirm:
        lines.append('import { ConfirmDelete } from "../components/ConfirmDelete";')
    if printer.forms:
        lines.append('import { useFormState } from "../forms";')
    if printer.data_imports:
        lines.append(f'import {{ {", ".join(sorted(printer.data_imports))} }} from "../data/entities";')
    if printer.store_imports:
        lines.append(f'import {{ {", ".join(sorted(printer.store_imports))} }} from "../data/store";')
    if has_layout:
        lines.append('import { useLayoutStyles } from "../layout";')
    lines.append("")
    constants = printer.label_constants()
    if constants:
        lines.extend(constants)
        lines.append("")
    name = f"{pascal(screen.screen_id)}Screen"
    lines.append(f"export function {name}() {{")
    if has_layout:
        lines.append("  const layout = useLayoutStyles();")
    lines.extend(f"  {declaration}" for declaration in printer.declarations())
    lines.append("  return (")
    lines.append("    <>")
    lines.extend(body)
    lines.append("    </>")
    lines.append("  );")
    lines.append("}")
    return "\n".join(lines) + "\n"


_FORMS = """import { useState, type FormEvent } from "react";

/**
 * Form state for a generated form: the browser checks the constraints from the specification
 * (required, min, max, lengths, pattern); invalid fields get their message shown by Fluent Field.
 * Forms bound to an entity pass `save`, which stores the record (see src/data); its errors are shown.
 */
export function useFormState(options: { save?: (data: FormData) => Promise<void> | void } = {}) {
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = event.currentTarget;
    const next: Record<string, string> = {};
    for (const element of Array.from(form.elements)) {
      if (
        (element instanceof HTMLInputElement ||
          element instanceof HTMLSelectElement ||
          element instanceof HTMLTextAreaElement) &&
        element.name &&
        !element.validity.valid
      ) {
        next[element.name] = element.validationMessage;
      }
    }
    setErrors(next);
    setSaveError(null);
    if (Object.keys(next).length > 0) {
      setSubmitted(false);
      return;
    }
    if (options.save) {
      setSaving(true);
      try {
        await options.save(new FormData(form));
      } catch (error) {
        setSaveError(error instanceof Error ? error.message : "Saving failed.");
        setSaving(false);
        return;
      }
      setSaving(false);
    }
    setSubmitted(true);
  };

  return { errors, submitted, saveError, saving, onSubmit };
}
"""

_CONFIRM = """import {
  Button,
  Dialog,
  DialogActions,
  DialogBody,
  DialogContent,
  DialogSurface,
  DialogTitle,
  DialogTrigger,
} from "@fluentui/react-components";
import { useState } from "react";

/** Destructive actions are confirmed in a dialog (ADR-0014). */
export function ConfirmDelete({ name, onConfirm }: { name: string; onConfirm: () => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const confirm = async () => {
    try {
      await onConfirm();
      setOpen(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Deleting failed.");
    }
  };
  return (
    <Dialog open={open} onOpenChange={(_, data) => setOpen(data.open)}>
      <DialogTrigger disableButtonEnhancement>
        <Button size="small" aria-label={`Delete ${name}`}>
          Delete
        </Button>
      </DialogTrigger>
      <DialogSurface>
        <DialogBody>
          <DialogTitle>{`Delete ${name}?`}</DialogTitle>
          <DialogContent>{error ?? "This cannot be undone."}</DialogContent>
          <DialogActions>
            <DialogTrigger disableButtonEnhancement>
              <Button appearance="secondary">Keep</Button>
            </DialogTrigger>
            <Button appearance="primary" onClick={() => void confirm()}>
              Delete
            </Button>
          </DialogActions>
        </DialogBody>
      </DialogSurface>
    </Dialog>
  );
}
"""


_LAYOUT = """import { makeStyles, tokens } from "@fluentui/react-components";

export const useLayoutStyles = makeStyles({
  form: { display: "grid", gap: tokens.spacingVerticalM, maxWidth: "560px" },
  actions: { display: "flex", gap: tokens.spacingHorizontalS, flexWrap: "wrap" },
  section: { display: "grid", gap: tokens.spacingVerticalS },
  unsupported: {
    padding: tokens.spacingVerticalS,
    border: `${tokens.strokeWidthThin} dashed ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    color: tokens.colorNeutralForeground2,
  },
});
"""


def _app_file(screens: list[RenderedScreen], header: str, app_name: str) -> str:
    imports = [
        f'import {{ {pascal(s.screen_id)}Screen }} from "./screens/{pascal(s.screen_id)}Screen";' for s in screens
    ]
    entries = [
        f"  {{ path: {literal(s.route)}, label: {literal(s.title)}, element: <{pascal(s.screen_id)}Screen /> }},"
        for s in screens
    ]
    fallback = (
        f'          <Route path="*" element={{<Navigate to={{{literal(screens[0].route)}}} replace />}} />'
        if screens
        else '          <Route path="*" element={<Body1>No screens are specified yet.</Body1>} />'
    )
    return (
        header
        + "\n"
        + f"import {{ {'' if screens else 'Body1, '}FluentProvider, Title3, makeStyles, tokens }} "
        + 'from "@fluentui/react-components";\n'
        + 'import type { ReactElement } from "react";\n'
        + f"import {{ BrowserRouter, NavLink, {'Navigate, ' if screens else ''}Route, Routes }} "
        + 'from "react-router-dom";\n'
        + 'import { appTheme } from "./theme";\n'
        + "\n".join(imports)
        + ("\n" if imports else "")
        + "\n"
        + "const SCREENS: { path: string; label: string; element: ReactElement }[] = [\n"
        + "\n".join(entries)
        + ("\n" if entries else "")
        + "];\n\n"
        + "const useStyles = makeStyles({\n"
        + '  shell: { display: "grid", gridTemplateColumns: "minmax(180px, 240px) 1fr", minHeight: "100vh" },\n'
        + "  nav: {\n"
        + "    padding: tokens.spacingHorizontalL,\n"
        + "    backgroundColor: tokens.colorNeutralBackground2,\n"
        + "    borderRight: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,\n"
        + "  },\n"
        + '  list: { listStyleType: "none", margin: 0, padding: 0, display: "grid", gap: tokens.spacingVerticalS },\n'
        + "  link: { color: tokens.colorBrandForegroundLink },\n"
        + "  main: {\n"
        + "    padding: tokens.spacingHorizontalXXL,\n"
        + '    display: "grid",\n'
        + "    gap: tokens.spacingVerticalL,\n"
        + '    alignContent: "start",\n'
        + "    minWidth: 0,\n"
        + "  },\n"
        + "});\n\n"
        + "export function App() {\n"
        + "  const styles = useStyles();\n"
        + "  return (\n"
        + "    <FluentProvider theme={appTheme}>\n"
        + "      <BrowserRouter>\n"
        + "        <div className={styles.shell}>\n"
        + '          <nav aria-label="Screens" className={styles.nav}>\n'
        + f'            <Title3 as="p">{{{literal(app_name)}}}</Title3>\n'
        + "            <ul className={styles.list}>\n"
        + "              {SCREENS.map((s) => (\n"
        + "                <li key={s.path}>\n"
        + "                  <NavLink className={styles.link} to={s.path}>\n"
        + "                    {s.label}\n"
        + "                  </NavLink>\n"
        + "                </li>\n"
        + "              ))}\n"
        + "            </ul>\n"
        + "          </nav>\n"
        + "          <main className={styles.main}>\n"
        + "            <Routes>\n"
        + "              {SCREENS.map((s) => (\n"
        + "                <Route key={s.path} path={s.path} element={s.element} />\n"
        + "              ))}\n"
        + fallback.replace("          <Route", "              <Route")
        + "\n"
        + "            </Routes>\n"
        + "          </main>\n"
        + "        </div>\n"
        + "      </BrowserRouter>\n"
        + "    </FluentProvider>\n"
        + "  );\n"
        + "}\n"
    )


def _static_files(name: str, title: str, header: str) -> dict[str, str]:
    tools = toolchain()
    package = {
        "name": name,
        "private": True,
        "version": "0.1.0",
        "type": "module",
        "engines": {"node": tools["node"]},
        "scripts": {
            "dev": "vite",
            "build": "tsc -p tsconfig.json && vite build",
            "preview": "vite preview",
            "typecheck": "tsc -p tsconfig.json",
        },
        "dependencies": tools["dependencies"],
        "devDependencies": tools["devDependencies"],
    }
    tsconfig = {
        "compilerOptions": {
            "target": "ES2022",
            "lib": ["ES2022", "DOM", "DOM.Iterable"],
            "module": "ESNext",
            "moduleResolution": "Bundler",
            "jsx": "react-jsx",
            "strict": True,
            "noUncheckedIndexedAccess": True,
            "noUnusedLocals": True,
            "noUnusedParameters": True,
            "isolatedModules": True,
            "skipLibCheck": True,
            "types": ["vite/client"],
            "noEmit": True,
        },
        "include": ["src"],
    }
    html_title = html.escape(" ".join(title.split()))
    return {
        "package.json": json.dumps(package, indent=2) + "\n",
        "tsconfig.json": json.dumps(tsconfig, indent=2) + "\n",
        "vite.config.ts": header
        + '\nimport react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\n'
        + "export default defineConfig({ plugins: [react()] });\n",
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{html_title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            '    <div id="root"></div>\n'
            '    <script type="module" src="/src/main.tsx"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "src/main.tsx": header
        + '\nimport { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\n'
        + 'import { App } from "./App";\n\n'
        + 'const root = document.getElementById("root");\n'
        + 'if (!root) throw new Error("missing #root");\n'
        + "createRoot(root).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n",
        "src/layout.ts": header + "\n" + _LAYOUT,
        "src/forms.ts": header + "\n" + _FORMS,
        "src/components/ConfirmDelete.tsx": header + "\n" + _CONFIRM,
        ".gitignore": "node_modules/\ndist/\n",
    }


def _readme(
    title: str, spec_revision: int | None, contract: DesignSystemContract, screens: list[RenderedScreen]
) -> str:
    rows = "\n".join(f"| `{s.route}` | {s.title.replace('|', '/')} |" for s in screens) or "| — | No screens yet |"
    return (
        f"# {title.replace(chr(10), ' ')}\n\n"
        f"Generated by `{GENERATOR}@{GENERATOR_VERSION}` from specification revision "
        f"{spec_revision if spec_revision is not None else '(unsaved)'}, UI IR v1, design system "
        f"`{contract.id}@{contract.version}` ({contract.library.package} {contract.library.version}).\n\n"
        "This is a **static** application: screens, fields, tables and actions as specified, styled with\n"
        "Fluent 2 tokens. Forms do not submit and tables show their empty state; data access and\n"
        "behaviour are generated in later milestones.\n\n"
        "```bash\nnpm install\nnpm run dev      # http://localhost:5173\nnpm run build\n```\n\n"
        "| Route | Screen |\n|---|---|\n"
        f"{rows}\n"
    )


def _bindings(spec: ApplicationSpec, document: UiDocument) -> DataBindings:
    ir_nodes: dict[str, object] = {}
    list_routes: dict[str, str] = {}
    for screen in document.screens:
        for _, node in walk(screen.body, ""):
            ir_nodes[node.id] = node
            if isinstance(node, IrForm):
                for f in node.fields:
                    ir_nodes[f.id] = f
            if isinstance(node, IrTable) and node.entity_id and node.entity_id not in list_routes:
                list_routes[node.entity_id] = screen.route
    return DataBindings(
        ir_nodes=ir_nodes,
        entities={e.id for e in spec.entities if e.fields},
        references={
            (e.id, f.name): f.reference_entity_id for e in spec.entities for f in e.fields if f.reference_entity_id
        },
        list_routes=list_routes,
        screen_routes={s.id: s.route for s in document.screens},
    )


def theme_ts(header: str, theme: BrandTheme | None) -> str:
    """The Fluent theme the app renders with: Fluent's light theme, or an organization brand theme."""
    if theme is None:
        return (
            header
            + "\n"
            + 'import { webLightTheme, type Theme } from "@fluentui/react-components";\n\n'
            + "/** Fluent 2's default light theme. An organization brand theme replaces this file's contents. */\n"
            + "export const appTheme: Theme = webLightTheme;\n"
        )
    ramp = brand_ramp(theme.brand_color)
    variants = "\n".join(f"  {step}: {literal(color)}," for step, color in ramp.items())
    overrides = [f"  borderRadiusMedium: {literal(theme.fluent_radius)},"]
    if theme.font_family:
        overrides.insert(0, f"  fontFamilyBase: {literal(theme.font_family)},")
    return (
        header
        + "\n"
        + 'import { createLightTheme, type BrandVariants, type Theme } from "@fluentui/react-components";\n\n'
        + f"/** Organization brand theme {literal(theme.name)} ({literal(theme.selector)}) on Fluent 2. */\n"
        + "const brand: BrandVariants = {\n"
        + variants
        + "\n};\n\n"
        + "export const appTheme: Theme = {\n"
        + "  ...createLightTheme(brand),\n"
        + "\n".join(overrides)
        + "\n};\n"
    )


def generate_project(
    spec: ApplicationSpec,
    contract: DesignSystemContract,
    *,
    spec_revision: int | None = None,
    document: UiDocument | None = None,
    theme: BrandTheme | None = None,
) -> GeneratedProject:
    document = document or derive_document(spec, spec_revision=spec_revision)
    issues = validate_document(document, spec)
    errors = [i for i in issues if i.severity == "error"]
    if errors:
        raise GenerationBlocked(errors)
    rendered = render_screens(document.screens, contract)
    header = _header(spec_revision, contract)
    title = spec.metadata.name
    files: dict[str, str] = {}
    files.update(_static_files(package_name(title), title, header))
    files["README.md"] = _readme(title, spec_revision, contract, rendered)
    files["src/App.tsx"] = _app_file(rendered, header, title)
    files["src/theme.ts"] = theme_ts(header, theme)
    bindings = _bindings(spec, document)
    files["src/data/store.ts"] = header + "\n" + STORE_TS
    files["src/data/entities.ts"] = entities_ts(spec, header)
    files["api/openapi.json"] = openapi_json(spec, f"{GENERATOR}@{GENERATOR_VERSION}", spec_revision)
    for screen in rendered:
        files[f"src/screens/{pascal(screen.screen_id)}Screen.tsx"] = _screen_file(screen, header, contract, bindings)
    project = GeneratedProject(
        generator=f"{GENERATOR}@{GENERATOR_VERSION}",
        spec_revision=spec_revision,
        design_system=design_system_label(contract, theme),
        files=dict(sorted(files.items())),
        warnings=[i for i in issues if i.severity == "warning"],
    )
    manifest = {
        "generator": project.generator,
        "spec_revision": spec_revision,
        "ui_ir_version": document.ir_version,
        "design_system": project.design_system,
        "library": f"{contract.library.package}@{contract.library.version}",
        "files": {path: project.sha256(path) for path in project.files},
    }
    project.files[MANIFEST] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    project.files = dict(sorted(project.files.items()))
    return project
