"""Generate a complete Vite + React + TypeScript + Fluent 2 project from a spec revision.

Deterministic: the same spec revision, design system and generator version give
byte-identical files (no timestamps, sorted keys, stable ordering), so diffs
between revisions show only real changes. Generation is refused while the UI IR
has errors (ADR-0013); warnings (placeholders) are carried into the output as
visible "not supported yet" markers.
"""

from __future__ import annotations

import hashlib
import html
import json
import re
from importlib import resources
from typing import Any

from pydantic import BaseModel, Field

from appspec import ApplicationSpec
from design_system import (
    DesignSystemContract,
    RenderedScreen,
    UiDocument,
    UiIssue,
    derive_document,
    render_screens,
    validate_document,
)

from .jsx import GenerationError, components_in, is_library_component, literal, needs_layout, print_nodes

GENERATOR = "codegen-react"
GENERATOR_VERSION = "0.1.0"
MANIFEST = "workspace-manifest.json"


class GenerationBlocked(Exception):
    """The UI IR has errors; code is not generated until they are fixed."""

    def __init__(self, issues: list[UiIssue]) -> None:
        super().__init__(f"{len(issues)} UI error(s) block code generation")
        self.issues = issues


class GeneratedProject(BaseModel):
    generator: str
    spec_revision: int | None
    design_system: str
    files: dict[str, str] = Field(description="Path -> content, in a stable order.")
    warnings: list[UiIssue] = Field(default_factory=list)

    def sha256(self, path: str) -> str:
        return hashlib.sha256(self.files[path].encode("utf-8")).hexdigest()


def toolchain() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(
        resources.files(__package__).joinpath("toolchain.json").read_text(encoding="utf-8")
    )
    return data


def pascal(identifier: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^a-zA-Z0-9]+", identifier) if part)


def package_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:60].strip("-")
    return f"{slug}-app" if slug and slug[0].isalpha() else "generated-app"


def _header(spec_revision: int | None, contract: DesignSystemContract) -> str:
    revision = f"r{spec_revision}" if spec_revision is not None else "an unsaved spec"
    return (
        f"// Generated by {GENERATOR}@{GENERATOR_VERSION} from spec {revision} "
        f"(UI IR v1, design system {contract.id}@{contract.version}).\n"
        "// Do not edit by hand yet: regeneration replaces this file (edit preservation is Milestone 5).\n"
    )


def _screen_file(screen: RenderedScreen, header: str, contract: DesignSystemContract) -> str:
    used = components_in(screen.root)
    library = sorted(c for c in used if is_library_component(c))
    packages = {m.package for m in contract.mappings.values()} - {"html"}
    if len(packages) != 1:
        raise GenerationError("expected exactly one component package in the contract")
    [package] = packages
    has_form = "form" in used
    has_layout = needs_layout(screen.root)
    lines = [header.rstrip("\n"), ""]
    if library:
        lines.append(f"import {{ {', '.join(library)} }} from {literal(package)};")
    if has_form:
        lines.append('import type { FormEvent } from "react";')
    if has_layout:
        lines.append('import { useLayoutStyles } from "../layout";')
    lines.append("")
    if has_form:
        lines.append("// Static screen: submitting does nothing until behaviour is generated (Milestone 5).")
        lines.append("const preventSubmit = (event: FormEvent) => event.preventDefault();")
        lines.append("")
    name = f"{pascal(screen.screen_id)}Screen"
    lines.append(f"export function {name}() {{")
    if has_layout:
        lines.append("  const layout = useLayoutStyles();")
    lines.append("  return (")
    lines.append("    <>")
    lines.extend(print_nodes(screen.root, 3))
    lines.append("    </>")
    lines.append("  );")
    lines.append("}")
    return "\n".join(lines) + "\n"


_LAYOUT = """import { makeStyles, tokens } from "@fluentui/react-components";

export const useLayoutStyles = makeStyles({
  form: { display: "grid", gap: tokens.spacingVerticalM, maxWidth: "560px" },
  actions: { display: "flex", gap: tokens.spacingHorizontalS, flexWrap: "wrap" },
  section: { display: "grid", gap: tokens.spacingVerticalS },
  unsupported: {
    padding: tokens.spacingVerticalS,
    border: `${tokens.strokeWidthThin} dashed ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    color: tokens.colorNeutralForeground2,
  },
});
"""


def _app_file(screens: list[RenderedScreen], header: str, app_name: str) -> str:
    imports = [
        f'import {{ {pascal(s.screen_id)}Screen }} from "./screens/{pascal(s.screen_id)}Screen";' for s in screens
    ]
    entries = [
        f"  {{ path: {literal(s.route)}, label: {literal(s.title)}, element: <{pascal(s.screen_id)}Screen /> }},"
        for s in screens
    ]
    fallback = (
        f'          <Route path="*" element={{<Navigate to={{{literal(screens[0].route)}}} replace />}} />'
        if screens
        else '          <Route path="*" element={<Body1>No screens are specified yet.</Body1>} />'
    )
    return (
        header
        + "\n"
        + f"import {{ {'' if screens else 'Body1, '}FluentProvider, Title3, makeStyles, tokens, webLightTheme }} "
        + 'from "@fluentui/react-components";\n'
        + 'import type { ReactElement } from "react";\n'
        + f"import {{ BrowserRouter, NavLink, {'Navigate, ' if screens else ''}Route, Routes }} "
        + 'from "react-router-dom";\n'
        + "\n".join(imports)
        + ("\n" if imports else "")
        + "\n"
        + "const SCREENS: { path: string; label: string; element: ReactElement }[] = [\n"
        + "\n".join(entries)
        + ("\n" if entries else "")
        + "];\n\n"
        + "const useStyles = makeStyles({\n"
        + '  shell: { display: "grid", gridTemplateColumns: "minmax(180px, 240px) 1fr", minHeight: "100vh" },\n'
        + "  nav: {\n"
        + "    padding: tokens.spacingHorizontalL,\n"
        + "    backgroundColor: tokens.colorNeutralBackground2,\n"
        + "    borderRight: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,\n"
        + "  },\n"
        + '  list: { listStyleType: "none", margin: 0, padding: 0, display: "grid", gap: tokens.spacingVerticalS },\n'
        + "  link: { color: tokens.colorBrandForegroundLink },\n"
        + "  main: {\n"
        + "    padding: tokens.spacingHorizontalXXL,\n"
        + '    display: "grid",\n'
        + "    gap: tokens.spacingVerticalL,\n"
        + '    alignContent: "start",\n'
        + "    minWidth: 0,\n"
        + "  },\n"
        + "});\n\n"
        + "export function App() {\n"
        + "  const styles = useStyles();\n"
        + "  return (\n"
        + "    <FluentProvider theme={webLightTheme}>\n"
        + "      <BrowserRouter>\n"
        + "        <div className={styles.shell}>\n"
        + '          <nav aria-label="Screens" className={styles.nav}>\n'
        + f'            <Title3 as="p">{{{literal(app_name)}}}</Title3>\n'
        + "            <ul className={styles.list}>\n"
        + "              {SCREENS.map((s) => (\n"
        + "                <li key={s.path}>\n"
        + "                  <NavLink className={styles.link} to={s.path}>\n"
        + "                    {s.label}\n"
        + "                  </NavLink>\n"
        + "                </li>\n"
        + "              ))}\n"
        + "            </ul>\n"
        + "          </nav>\n"
        + "          <main className={styles.main}>\n"
        + "            <Routes>\n"
        + "              {SCREENS.map((s) => (\n"
        + "                <Route key={s.path} path={s.path} element={s.element} />\n"
        + "              ))}\n"
        + fallback.replace("          <Route", "              <Route")
        + "\n"
        + "            </Routes>\n"
        + "          </main>\n"
        + "        </div>\n"
        + "      </BrowserRouter>\n"
        + "    </FluentProvider>\n"
        + "  );\n"
        + "}\n"
    )


def _static_files(name: str, title: str, header: str) -> dict[str, str]:
    tools = toolchain()
    package = {
        "name": name,
        "private": True,
        "version": "0.1.0",
        "type": "module",
        "engines": {"node": tools["node"]},
        "scripts": {
            "dev": "vite",
            "build": "tsc -p tsconfig.json && vite build",
            "preview": "vite preview",
            "typecheck": "tsc -p tsconfig.json",
        },
        "dependencies": tools["dependencies"],
        "devDependencies": tools["devDependencies"],
    }
    tsconfig = {
        "compilerOptions": {
            "target": "ES2022",
            "lib": ["ES2022", "DOM", "DOM.Iterable"],
            "module": "ESNext",
            "moduleResolution": "Bundler",
            "jsx": "react-jsx",
            "strict": True,
            "noUncheckedIndexedAccess": True,
            "noUnusedLocals": True,
            "noUnusedParameters": True,
            "isolatedModules": True,
            "skipLibCheck": True,
            "noEmit": True,
        },
        "include": ["src"],
    }
    html_title = html.escape(" ".join(title.split()))
    return {
        "package.json": json.dumps(package, indent=2) + "\n",
        "tsconfig.json": json.dumps(tsconfig, indent=2) + "\n",
        "vite.config.ts": header
        + '\nimport react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\n'
        + "export default defineConfig({ plugins: [react()] });\n",
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{html_title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            '    <div id="root"></div>\n'
            '    <script type="module" src="/src/main.tsx"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "src/main.tsx": header
        + '\nimport { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\n'
        + 'import { App } from "./App";\n\n'
        + 'const root = document.getElementById("root");\n'
        + 'if (!root) throw new Error("missing #root");\n'
        + "createRoot(root).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n",
        "src/layout.ts": header + "\n" + _LAYOUT,
        ".gitignore": "node_modules/\ndist/\n",
    }


def _readme(
    title: str, spec_revision: int | None, contract: DesignSystemContract, screens: list[RenderedScreen]
) -> str:
    rows = "\n".join(f"| `{s.route}` | {s.title.replace('|', '/')} |" for s in screens) or "| — | No screens yet |"
    return (
        f"# {title.replace(chr(10), ' ')}\n\n"
        f"Generated by `{GENERATOR}@{GENERATOR_VERSION}` from specification revision "
        f"{spec_revision if spec_revision is not None else '(unsaved)'}, UI IR v1, design system "
        f"`{contract.id}@{contract.version}` ({contract.library.package} {contract.library.version}).\n\n"
        "This is a **static** application: screens, fields, tables and actions as specified, styled with\n"
        "Fluent 2 tokens. Forms do not submit and tables show their empty state; data access and\n"
        "behaviour are generated in later milestones.\n\n"
        "```bash\nnpm install\nnpm run dev      # http://localhost:5173\nnpm run build\n```\n\n"
        "| Route | Screen |\n|---|---|\n"
        f"{rows}\n"
    )


def generate_project(
    spec: ApplicationSpec,
    contract: DesignSystemContract,
    *,
    spec_revision: int | None = None,
    document: UiDocument | None = None,
) -> GeneratedProject:
    document = document or derive_document(spec, spec_revision=spec_revision)
    issues = validate_document(document, spec)
    errors = [i for i in issues if i.severity == "error"]
    if errors:
        raise GenerationBlocked(errors)
    rendered = render_screens(document.screens, contract)
    header = _header(spec_revision, contract)
    title = spec.metadata.name
    files: dict[str, str] = {}
    files.update(_static_files(package_name(title), title, header))
    files["README.md"] = _readme(title, spec_revision, contract, rendered)
    files["src/App.tsx"] = _app_file(rendered, header, title)
    for screen in rendered:
        files[f"src/screens/{pascal(screen.screen_id)}Screen.tsx"] = _screen_file(screen, header, contract)
    project = GeneratedProject(
        generator=f"{GENERATOR}@{GENERATOR_VERSION}",
        spec_revision=spec_revision,
        design_system=f"{contract.id}@{contract.version}",
        files=dict(sorted(files.items())),
        warnings=[i for i in issues if i.severity == "warning"],
    )
    manifest = {
        "generator": project.generator,
        "spec_revision": spec_revision,
        "ui_ir_version": document.ir_version,
        "design_system": project.design_system,
        "library": f"{contract.library.package}@{contract.library.version}",
        "files": {path: project.sha256(path) for path in project.files},
    }
    project.files[MANIFEST] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    project.files = dict(sorted(project.files.items()))
    return project
