from __future__ import annotations

import copy
import io
import json
import zipfile
from collections.abc import Callable
from typing import Any

import pytest
from fastapi.testclient import TestClient

pytestmark = pytest.mark.db

OTHER = {"X-Dev-Tenant": "globex", "X-Dev-User": "mallory"}


def put(client: TestClient, pid: str, spec: dict[str, Any], revision: int) -> None:
    response = client.put(f"/api/v1/projects/{pid}/spec", json={"spec": spec}, headers={"If-Match": f'"r{revision}"'})
    assert response.status_code == 200, response.text


@pytest.fixture
def pid(client: TestClient, make_project: Callable[..., dict[str, Any]], example_spec: dict[str, Any]) -> str:
    project_id = str(make_project("Finance ops")["id"])
    put(client, project_id, example_spec, 1)
    return project_id


def test_manifest_lists_generated_files_with_hashes(client: TestClient, pid: str) -> None:
    body = client.get(f"/api/v1/projects/{pid}/code").json()
    assert body["spec_revision"] == 2
    assert body["generator"] == "codegen-react@0.1.0"
    assert body["design_system"] == "fluent2@1.0.0"
    paths = [f["path"] for f in body["files"]]
    assert "src/screens/AdjustmentRulesScreen.tsx" in paths
    assert "workspace-manifest.json" in paths
    screen = next(f for f in body["files"] if f["path"] == "src/screens/AdjustmentRulesScreen.tsx")
    assert screen["language"] == "tsx"
    assert len(screen["sha256"]) == 64
    assert body["warnings"] == []


def test_single_file_and_unknown_paths(client: TestClient, pid: str) -> None:
    response = client.get(f"/api/v1/projects/{pid}/code/file", params={"path": "src/screens/AdjustmentRulesScreen.tsx"})
    assert response.status_code == 200
    content = response.json()["content"]
    assert content.startswith("// Generated by codegen-react@0.1.0 from spec r2")
    assert "export function AdjustmentRulesScreen()" in content
    assert client.get(f"/api/v1/projects/{pid}/code/file", params={"path": "../../etc/passwd"}).status_code == 404


def test_diff_between_revisions(client: TestClient, pid: str, example_spec: dict[str, Any]) -> None:
    spec = copy.deepcopy(example_spec)
    spec["entities"][0]["fields"].append({"name": "comment", "type": "text"})
    put(client, pid, spec, 2)
    body = client.get(f"/api/v1/projects/{pid}/code/diff", params={"from": 2}).json()
    assert (body["from_revision"], body["to_revision"]) == (2, 3)
    changed = {f["path"]: f for f in body["files"]}
    assert changed["src/screens/AdjustmentRulesScreen.tsx"]["status"] == "modified"
    assert '{"Comment"}' in changed["src/screens/AdjustmentRulesScreen.tsx"]["unified"]
    same = client.get(f"/api/v1/projects/{pid}/code/diff", params={"from": 3, "to": 3}).json()
    assert same["files"] == []
    # r1 is the empty spec: its app has no screens, so the screen file shows as added.
    first = client.get(f"/api/v1/projects/{pid}/code/diff", params={"from": 1, "to": 2}).json()
    assert {f["status"] for f in first["files"] if f["path"].startswith("src/screens/")} == {"added"}


def test_zip_download_is_deterministic(client: TestClient, pid: str) -> None:
    first = client.get(f"/api/v1/projects/{pid}/code.zip")
    assert first.status_code == 200
    assert first.headers["content-type"] == "application/zip"
    # The project name follows the spec ("Finance Operations Adjustments") once the spec is saved.
    assert first.headers["content-disposition"] == 'attachment; filename="finance-operations-adjustments-app-r2.zip"'
    assert client.get(f"/api/v1/projects/{pid}/code.zip").content == first.content
    with zipfile.ZipFile(io.BytesIO(first.content)) as zf:
        names = zf.namelist()
        assert "finance-operations-adjustments-app-r2/package.json" in names
        package = json.loads(zf.read("finance-operations-adjustments-app-r2/package.json"))
        assert package["dependencies"]["@fluentui/react-components"] == "9.74.9"


def test_ui_errors_block_generation(client: TestClient, pid: str, example_spec: dict[str, Any]) -> None:
    spec = copy.deepcopy(example_spec)
    # A component whose id collides with the derived title heading makes the IR invalid (duplicate node id).
    spec["screens"][0]["components"][0]["id"] = "title"
    put(client, pid, spec, 2)
    response = client.get(f"/api/v1/projects/{pid}/code")
    assert response.status_code == 422
    body = response.json()
    assert body["type"] == "urn:workspace:error:code-generation-blocked"
    assert [e["code"] for e in body["errors"]] == ["id-duplicate"]
    assert client.get(f"/api/v1/projects/{pid}/code.zip").status_code == 422
    # The previous revision still generates.
    assert client.get(f"/api/v1/projects/{pid}/code", params={"revision": 2}).status_code == 200


def test_code_is_tenant_scoped(client: TestClient, pid: str) -> None:
    assert client.get(f"/api/v1/projects/{pid}/code", headers=OTHER).status_code == 404
    assert client.get(f"/api/v1/projects/{pid}/code.zip", headers=OTHER).status_code == 404
