/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects, newest first */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create a project with an initial, empty specification (revision 1) */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project audit trail */
        get: operations["list_audit_api_v1_projects__project_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current specification; the ETag identifies its revision */
        get: operations["get_spec_api_v1_projects__project_id__spec_get"];
        /** Save a new specification revision (optimistic concurrency via If-Match) */
        put: operations["put_spec_api_v1_projects__project_id__spec_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List specification revisions, newest first */
        get: operations["list_revisions_api_v1_projects__project_id__spec_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec/revisions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific specification revision */
        get: operations["get_revision_api_v1_projects__project_id__spec_revisions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a candidate specification without saving it */
        post: operations["validate_spec_api_v1_projects__project_id__spec_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schemas/application-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JSON Schema of the current specification version */
        get: operations["application_spec_schema_api_v1_schemas_application_spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (database reachable) */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptanceCriterion */
        AcceptanceCriterion: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Given */
            given: string;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            /**
             * Requirement Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            requirement_id: string;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
            /** Then */
            then: string;
            /** When */
            when: string;
        };
        /** AccessibilityRequirements */
        AccessibilityRequirements: {
            /** Notes */
            notes?: string[];
            standard?: components["schemas"]["Tracked_Literal_1_AA__2_AA__2_AAA___"];
        };
        /** ApplicationSpec */
        "ApplicationSpec-Input": {
            /** Acceptance Criteria */
            acceptance_criteria?: components["schemas"]["AcceptanceCriterion"][];
            accessibility?: components["schemas"]["AccessibilityRequirements"];
            /** Artifact Dependencies */
            artifact_dependencies?: components["schemas"]["ArtifactDependency"][];
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
            /** Authorization */
            authorization?: components["schemas"]["AuthorizationRule"][];
            /** Business Rules */
            business_rules?: components["schemas"]["BusinessRule"][];
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            design_system?: components["schemas"]["DesignSystemSelection"];
            domain?: components["schemas"]["appspec__common__Tracked_Annotated_str__StringConstraints____2"];
            /** Entities */
            entities?: components["schemas"]["DataEntity"][];
            framework?: components["schemas"]["FrameworkConfig"];
            /** Functional Requirements */
            functional_requirements?: components["schemas"]["FunctionalRequirement"][];
            /** Integrations */
            integrations?: components["schemas"]["IntegrationContract"][];
            /** Journeys */
            journeys?: components["schemas"]["UserJourney"][];
            metadata: components["schemas"]["ProjectMetadata"];
            /** Navigation */
            navigation?: components["schemas"]["NavigationItem-Input"][];
            /** Nonfunctional Requirements */
            nonfunctional_requirements?: components["schemas"]["NonFunctionalRequirement"][];
            objective?: components["schemas"]["appspec__common__Tracked_Annotated_str__StringConstraints____1"];
            /** Open Questions */
            open_questions?: components["schemas"]["OpenQuestion"][];
            /** Org Constraints */
            org_constraints?: components["schemas"]["DesignConstraint"][];
            /** Personas */
            personas?: components["schemas"]["Persona"][];
            /** Responsive */
            responsive?: components["schemas"]["ResponsiveRule"][];
            /** Roles */
            roles?: components["schemas"]["Role"][];
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Screens */
            screens?: components["schemas"]["Screen"][];
            security?: components["schemas"]["SecurityProfile"];
        };
        /** ApplicationSpec */
        "ApplicationSpec-Output": {
            /** Acceptance Criteria */
            acceptance_criteria?: components["schemas"]["AcceptanceCriterion"][];
            accessibility?: components["schemas"]["AccessibilityRequirements"];
            /** Artifact Dependencies */
            artifact_dependencies?: components["schemas"]["ArtifactDependency"][];
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
            /** Authorization */
            authorization?: components["schemas"]["AuthorizationRule"][];
            /** Business Rules */
            business_rules?: components["schemas"]["BusinessRule"][];
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            design_system?: components["schemas"]["DesignSystemSelection"];
            domain?: components["schemas"]["appspec__common__Tracked_Annotated_str__StringConstraints____2"];
            /** Entities */
            entities?: components["schemas"]["DataEntity"][];
            framework?: components["schemas"]["FrameworkConfig"];
            /** Functional Requirements */
            functional_requirements?: components["schemas"]["FunctionalRequirement"][];
            /** Integrations */
            integrations?: components["schemas"]["IntegrationContract"][];
            /** Journeys */
            journeys?: components["schemas"]["UserJourney"][];
            metadata: components["schemas"]["ProjectMetadata"];
            /** Navigation */
            navigation?: components["schemas"]["NavigationItem-Output"][];
            /** Nonfunctional Requirements */
            nonfunctional_requirements?: components["schemas"]["NonFunctionalRequirement"][];
            objective?: components["schemas"]["appspec__common__Tracked_Annotated_str__StringConstraints____1"];
            /** Open Questions */
            open_questions?: components["schemas"]["OpenQuestion"][];
            /** Org Constraints */
            org_constraints?: components["schemas"]["DesignConstraint"][];
            /** Personas */
            personas?: components["schemas"]["Persona"][];
            /** Responsive */
            responsive?: components["schemas"]["ResponsiveRule"][];
            /** Roles */
            roles?: components["schemas"]["Role"][];
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Screens */
            screens?: components["schemas"]["Screen"][];
            security?: components["schemas"]["SecurityProfile"];
        };
        /** ArtifactDependency */
        ArtifactDependency: {
            /**
             * From Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            from_id: string;
            /**
             * Kind
             * @default derives-from
             * @enum {string}
             */
            kind: "derives-from" | "implements" | "constrains" | "tests";
            /**
             * To Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            to_id: string;
        };
        /** Assumption */
        Assumption: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            /** Related Ids */
            related_ids?: string[];
            revision?: components["schemas"]["RevisionMeta"];
            /** Statement */
            statement: string;
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AuthorizationRule */
        AuthorizationRule: {
            /** Actions */
            actions: ("create" | "read" | "update" | "delete" | "approve" | "execute" | "export")[];
            /** Condition */
            condition?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            /** Resource */
            resource: string;
            revision?: components["schemas"]["RevisionMeta"];
            /**
             * Role Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            role_id: string;
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** BusinessRule */
        BusinessRule: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            /** Requirement Ids */
            requirement_ids?: string[];
            revision?: components["schemas"]["RevisionMeta"];
            /** Statement */
            statement: string;
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /**
         * Classification
         * @enum {string}
         */
        Classification: "public" | "internal" | "confidential" | "restricted";
        /** CollectionSummary */
        CollectionSummary: {
            /** Confirmed */
            confirmed: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Proposed */
            proposed: number;
        };
        /**
         * ComponentSpec
         * @description Semantic component intent; mapped to design-system components later.
         */
        ComponentSpec: {
            /** Entity Id */
            entity_id?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "form" | "table" | "card" | "metric" | "chart" | "dialog" | "tabs" | "list" | "toolbar" | "notification" | "text" | "other";
            /** Label */
            label?: string | null;
        };
        /** DataEntity */
        DataEntity: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Description */
            description?: string | null;
            /** Fields */
            fields?: components["schemas"]["EntityField"][];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Name */
            name: string;
            provenance: components["schemas"]["Provenance"];
            /** Relationships */
            relationships?: components["schemas"]["Relationship"][];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** Decision */
        Decision: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            /** Rationale */
            rationale?: string | null;
            /** Related Ids */
            related_ids?: string[];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
            /** Summary */
            summary: string;
        };
        /** DesignConstraint */
        DesignConstraint: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** Statement */
            statement: string;
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** DesignSystemSelection */
        DesignSystemSelection: {
            id?: components["schemas"]["Tracked_Annotated_str__StringConstraints__FieldInfo_annotation_NoneType__required_True__description__Stable__human-readable_identifier__lowercase_kebab-case_____"];
            version?: components["schemas"]["appspec__common__Tracked_Annotated_str__StringConstraints____2"];
        };
        /** EntityField */
        EntityField: {
            /** Description */
            description?: string | null;
            /** Enum Values */
            enum_values?: string[];
            /**
             * Name
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            name: string;
            /** Reference Entity Id */
            reference_entity_id?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            type: components["schemas"]["FieldType"];
        };
        /**
         * FactStatus
         * @enum {string}
         */
        FactStatus: "unknown" | "proposed" | "confirmed";
        /** FactSummary */
        FactSummary: {
            /** Label */
            label: string;
            /** Path */
            path: string;
            status: components["schemas"]["FactStatus"];
        };
        /** FieldError */
        FieldError: {
            /** Code */
            code?: string | null;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "string" | "text" | "integer" | "decimal" | "money" | "boolean" | "date" | "datetime" | "enum" | "file" | "reference";
        /** FormField */
        FormField: {
            /** Help Text */
            help_text?: string | null;
            /** Label */
            label: string;
            /**
             * Name
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            name: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            type: components["schemas"]["FieldType"];
            /** Validation */
            validation?: components["schemas"]["ValidationRule"][];
        };
        /**
         * Framework
         * @enum {string}
         */
        Framework: "react" | "angular";
        /** FrameworkConfig */
        FrameworkConfig: {
            framework?: components["schemas"]["Tracked_Framework_"];
            /**
             * Language
             * @default typescript
             * @constant
             */
            language: "typescript";
        };
        /** FunctionalRequirement */
        FunctionalRequirement: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Persona Ids */
            persona_ids?: string[];
            /** @default should */
            priority: components["schemas"]["Priority"];
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
            /** Title */
            title: string;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** IntegrationContract */
        IntegrationContract: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "inbound" | "outbound" | "bidirectional";
            /** Entity Ids */
            entity_ids?: string[];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "rest" | "graphql" | "file" | "event" | "database" | "other";
            /** Name */
            name: string;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "proposed" | "confirmed";
        /** JourneyStep */
        JourneyStep: {
            /** Description */
            description: string;
            /** Screen Id */
            screen_id?: string | null;
        };
        /** NavigationItem */
        "NavigationItem-Input": {
            /** Children */
            children?: components["schemas"]["NavigationItem-Input"][];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Label */
            label: string;
            /** Screen Id */
            screen_id?: string | null;
        };
        /** NavigationItem */
        "NavigationItem-Output": {
            /** Children */
            children?: components["schemas"]["NavigationItem-Output"][];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Label */
            label: string;
            /** Screen Id */
            screen_id?: string | null;
        };
        /**
         * NfrCategory
         * @enum {string}
         */
        NfrCategory: "performance" | "availability" | "security" | "privacy" | "compliance" | "accessibility" | "usability" | "scalability" | "observability" | "maintainability" | "other";
        /** NonFunctionalRequirement */
        NonFunctionalRequirement: {
            category: components["schemas"]["NfrCategory"];
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /**
             * Measure
             * @description How compliance is measured, e.g. 'p95 < 300 ms'.
             */
            measure?: string | null;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** Statement */
            statement: string;
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** OpenQuestion */
        OpenQuestion: {
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Question */
            question: string;
            /** Related Ids */
            related_ids?: string[];
        };
        /** Persona */
        Persona: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Description */
            description?: string | null;
            /** Goals */
            goals?: string[];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Name */
            name: string;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** Role Ids */
            role_ids?: string[];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "must" | "should" | "could" | "wont";
        /** Problem */
        Problem: {
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][];
            /** Extensions */
            extensions?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @description Stable error code URI, e.g. 'urn:workspace:error:revision-conflict'.
             */
            type: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** ProjectMetadata */
        ProjectMetadata: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Tags */
            tags?: string[];
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Current Revision */
            current_revision: number;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectPage */
        ProjectPage: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when there are no more.
             */
            next_cursor: string | null;
        };
        /**
         * Provenance
         * @description Where a value came from. Model-sourced values record the producing skill and model.
         */
        Provenance: {
            /**
             * Actor
             * @description User or service identity that supplied the value.
             */
            actor?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Note */
            note?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Skill Id */
            skill_id?: string | null;
            /** Skill Version */
            skill_version?: string | null;
            source: components["schemas"]["Source"];
        };
        /** Relationship */
        Relationship: {
            /** Description */
            description?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
            /**
             * Target Entity Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            target_entity_id: string;
        };
        /** ResponsiveRule */
        ResponsiveRule: {
            /** Behavior */
            behavior: string;
            /**
             * Breakpoint
             * @enum {string}
             */
            breakpoint: "mobile" | "tablet" | "desktop" | "wide";
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /**
         * RevisionMeta
         * @description Server-stamped revision bookkeeping. Client-supplied values are overwritten.
         */
        RevisionMeta: {
            /** Created In */
            created_in?: number | null;
            /** Updated In */
            updated_in?: number | null;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /** Role */
        Role: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Name */
            name: string;
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** Screen */
        Screen: {
            /** Components */
            components?: components["schemas"]["ComponentSpec"][];
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Fields */
            fields?: components["schemas"]["FormField"][];
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Name */
            name: string;
            /** Persona Ids */
            persona_ids?: string[];
            provenance: components["schemas"]["Provenance"];
            /** Purpose */
            purpose?: string | null;
            /** Requirement Ids */
            requirement_ids?: string[];
            revision?: components["schemas"]["RevisionMeta"];
            /** States */
            states?: components["schemas"]["UiState"][];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
        };
        /** SecurityProfile */
        SecurityProfile: {
            classification?: components["schemas"]["Tracked_Classification_"];
            risk_level?: components["schemas"]["Tracked_RiskLevel_"];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "error" | "warning";
        /**
         * Source
         * @enum {string}
         */
        Source: "user" | "model" | "derived" | "system";
        /** SpecRevisionMeta */
        SpecRevisionMeta: {
            /** Change Summary */
            change_summary: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: string;
        };
        /** SpecRevisionOut */
        SpecRevisionOut: {
            /** Change Summary */
            change_summary: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Issues
             * @description Non-blocking warnings for the stored revision.
             */
            issues: components["schemas"]["ValidationIssue"][];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: string;
            spec: components["schemas"]["ApplicationSpec-Output"];
            summary: components["schemas"]["SpecSummary"];
        };
        /** SpecRevisionPage */
        SpecRevisionPage: {
            /** Items */
            items: components["schemas"]["SpecRevisionMeta"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SpecSummary */
        SpecSummary: {
            /** Blocking Questions */
            blocking_questions: number;
            /** Collections */
            collections: components["schemas"]["CollectionSummary"][];
            /** Confirmed Facts */
            confirmed_facts: number;
            /** Facts */
            facts: components["schemas"]["FactSummary"][];
            /** Open Questions */
            open_questions: number;
            /** Total Facts */
            total_facts: number;
        };
        /** SpecUpdate */
        SpecUpdate: {
            /** Change Summary */
            change_summary?: string | null;
            spec: components["schemas"]["ApplicationSpec-Input"];
        };
        /** SpecValidationResult */
        SpecValidationResult: {
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            summary: components["schemas"]["SpecSummary"];
            /** Valid */
            valid: boolean;
        };
        /** Tracked[Annotated[str, StringConstraints, FieldInfo(annotation=NoneType, required=True, description='Stable, human-readable identifier (lowercase kebab-case, max 64 chars).')]] */
        "Tracked_Annotated_str__StringConstraints__FieldInfo_annotation_NoneType__required_True__description__Stable__human-readable_identifier__lowercase_kebab-case_____": {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            /** Value */
            value?: string | null;
        };
        /** Tracked[Classification] */
        Tracked_Classification_: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            value?: components["schemas"]["Classification"] | null;
        };
        /** Tracked[Framework] */
        Tracked_Framework_: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            value?: components["schemas"]["Framework"] | null;
        };
        /** Tracked[Literal['WCAG 2.1 AA', 'WCAG 2.2 AA', 'WCAG 2.2 AAA']] */
        Tracked_Literal_1_AA__2_AA__2_AAA___: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            /** Value */
            value?: ("WCAG 2.1 AA" | "WCAG 2.2 AA" | "WCAG 2.2 AAA") | null;
        };
        /** Tracked[RiskLevel] */
        Tracked_RiskLevel_: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            value?: components["schemas"]["RiskLevel"] | null;
        };
        /**
         * UiState
         * @enum {string}
         */
        UiState: "loading" | "empty" | "error" | "success" | "disabled";
        /** UserJourney */
        UserJourney: {
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Id
             * @description Stable, human-readable identifier (lowercase kebab-case, max 64 chars).
             */
            id: string;
            /** Name */
            name: string;
            /** Persona Ids */
            persona_ids?: string[];
            provenance: components["schemas"]["Provenance"];
            revision?: components["schemas"]["RevisionMeta"];
            /** @default proposed */
            status: components["schemas"]["ItemStatus"];
            /** Steps */
            steps?: components["schemas"]["JourneyStep"][];
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            severity: components["schemas"]["Severity"];
        };
        /** ValidationRule */
        ValidationRule: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "required" | "min" | "max" | "min-length" | "max-length" | "pattern" | "custom";
            /** Message */
            message?: string | null;
            /** Value */
            value?: string | number | null;
        };
        /** Tracked[Annotated[str, StringConstraints]] */
        appspec__common__Tracked_Annotated_str__StringConstraints____1: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            /** Value */
            value?: string | null;
        };
        /** Tracked[Annotated[str, StringConstraints]] */
        appspec__common__Tracked_Annotated_str__StringConstraints____2: {
            /** Confirmed By */
            confirmed_by?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
            revision?: components["schemas"]["RevisionMeta"];
            /** @default unknown */
            status: components["schemas"]["FactStatus"];
            /** Value */
            value?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: number;
                /** @description Opaque cursor from a previous page. */
                cursor?: string | null;
            };
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Replay of an earlier request with the same Idempotency-Key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_audit_api_v1_projects__project_id__audit_get: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: number;
                /** @description Opaque cursor from a previous page. */
                cursor?: string | null;
            };
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_spec_api_v1_projects__project_id__spec_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecRevisionOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    put_spec_api_v1_projects__project_id__spec_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecRevisionOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_revisions_api_v1_projects__project_id__spec_revisions_get: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: number;
                /** @description Opaque cursor from a previous page. */
                cursor?: string | null;
            };
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecRevisionPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_revision_api_v1_projects__project_id__spec_revisions__revision__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecRevisionOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    validate_spec_api_v1_projects__project_id__spec_validate_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Development only: tenant identifier. */
                "x-dev-tenant"?: string | null;
                /** @description Development only: user identifier. */
                "x-dev-user"?: string | null;
            };
            path: {
                /** @description Project identifier. */
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationSpec-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecValidationResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    application_spec_schema_api_v1_schemas_application_spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
}
