from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

from appspec import ApplicationSpec, load_spec
from codegen_react import (
    ALLOWED,
    MANIFEST,
    GenerationBlocked,
    GenerationError,
    diff_projects,
    generate_project,
    literal,
    package_name,
    pascal,
    toolchain,
)
from codegen_react.jsx import print_nodes
from design_system import RenderNode, UiDocument, get_contract
from design_system.ir import Form, Heading, Screen, ScreenSource

ROOT = Path(__file__).resolve().parents[3]
EXAMPLE = ROOT / "packages" / "application-spec" / "examples" / "finance-operations.json"
CONTRACT = get_contract("fluent2")
assert CONTRACT is not None


@pytest.fixture
def raw() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(EXAMPLE.read_text(encoding="utf-8"))
    return data


@pytest.fixture
def spec(raw: dict[str, Any]) -> ApplicationSpec:
    return load_spec(raw)


def test_project_layout_and_provenance(spec: ApplicationSpec) -> None:
    project = generate_project(spec, CONTRACT, spec_revision=4)
    assert list(project.files) == sorted(project.files)
    assert set(project.files) == {
        ".gitignore",
        "README.md",
        "api/openapi.json",
        "index.html",
        "package.json",
        "src/App.tsx",
        "src/components/ConfirmDelete.tsx",
        "src/data/entities.ts",
        "src/data/store.ts",
        "src/forms.ts",
        "src/layout.ts",
        "src/main.tsx",
        "src/screens/AdjustmentRulesScreen.tsx",
        "src/theme.ts",
        "tsconfig.json",
        "vite.config.ts",
        MANIFEST,
    }
    screen = project.files["src/screens/AdjustmentRulesScreen.tsx"]
    assert screen.startswith(
        "// Generated by codegen-react@0.6.0 from spec r4 (UI IR v1, design system fluent2@1.0.0)."
    )
    assert (
        "import { Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow, Title2 } "
        'from "@fluentui/react-components";' in screen
    )
    assert '<Table aria-label={"Adjustment"}>' in screen
    manifest = json.loads(project.files[MANIFEST])
    assert manifest["spec_revision"] == 4
    assert manifest["library"] == "@fluentui/react-components@9.74.9"
    assert set(manifest["files"]) == set(project.files) - {MANIFEST}
    assert manifest["files"]["src/App.tsx"] == project.sha256("src/App.tsx")


def test_generation_is_deterministic(spec: ApplicationSpec) -> None:
    assert (
        generate_project(spec, CONTRACT, spec_revision=2).files
        == generate_project(spec, CONTRACT, spec_revision=2).files
    )


def test_dependencies_are_pinned_exactly_to_the_workspace_lockfile() -> None:
    lock = json.loads((ROOT / "apps" / "workspace-web" / "package-lock.json").read_text(encoding="utf-8"))["packages"]
    tools = toolchain()
    for group in ("dependencies", "devDependencies"):
        for name, version in tools[group].items():
            assert re.fullmatch(r"\d+\.\d+\.\d+", version), f"{name} must be pinned exactly"
            assert lock[f"node_modules/{name}"]["version"] == version, name
    assert tools["dependencies"]["@fluentui/react-components"] == CONTRACT.library.version


def test_hostile_spec_text_stays_inside_string_literals(raw: dict[str, Any]) -> None:
    evil = 'Pwn"}</Title2><script>alert(1)</script>{`${process.env.X}`} */ \u2028 é'
    raw["metadata"]["name"] = evil
    raw["screens"][0]["name"] = evil
    raw["screens"][0]["components"][0]["label"] = evil
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=2)
    for path, content in project.files.items():
        if path.endswith((".tsx", ".ts")):
            # The text appears only as complete, escaped string literals; nothing of it is left as code.
            outside = content.replace(literal(evil), '""')
            assert "<script>" not in outside, path
            assert "process.env" not in outside, path
            assert "\u2028" not in content, path
    screen = project.files["src/screens/AdjustmentRulesScreen.tsx"]
    assert f'<Title2 as={{"h1"}}>{{{literal(evil)}}}</Title2>' in screen
    assert "&lt;script&gt;" in project.files["index.html"]
    assert re.fullmatch(r"pwn-[a-z0-9-]+-app", json.loads(project.files["package.json"])["name"])


def test_ir_errors_block_generation(spec: ApplicationSpec) -> None:
    broken = UiDocument(
        screens=[
            Screen(
                id="s",
                title="S",
                route="/s",
                source=ScreenSource(kind="spec-screen", ref="s"),
                body=[Heading(id="h", text="S", level=1), Form(id="f", label="F")],
            )
        ]
    )
    with pytest.raises(GenerationBlocked) as info:
        generate_project(spec, CONTRACT, document=broken)
    assert [i.code for i in info.value.issues] == ["form-empty"]


def test_printer_refuses_unknown_components_and_props() -> None:
    with pytest.raises(GenerationError, match="component 'script'"):
        print_nodes([RenderNode(component="script", text="x")], 0)
    with pytest.raises(GenerationError, match="prop 'onClick'"):
        print_nodes([RenderNode(component="Button", props={"onClick": "alert(1)"})], 0)
    with pytest.raises(GenerationError, match="invalid value"):
        print_nodes([RenderNode(component="Input", props={"type": "password"})], 0)


def test_entity_derived_app_has_routes_and_a_file_input_wired_to_field(raw: dict[str, Any]) -> None:
    raw["screens"], raw["navigation"] = [], []
    raw["entities"][1]["fields"].append({"name": "evidence", "type": "file"})
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    app = project.files["src/App.tsx"]
    for route in ('"/adjustment"', '"/adjustment/new"', '"/transaction"', '"/transaction/new"'):
        assert f"path: {route}" in app
    assert '<Navigate to={"/adjustment"} replace />' in app
    form = project.files["src/screens/TransactionFormScreen.tsx"]
    assert '{(fieldProps) => <input {...fieldProps} name={"evidence"} type={"file"} />}' in form


def test_diff_between_revisions_shows_only_real_changes(raw: dict[str, Any]) -> None:
    before = generate_project(load_spec(raw), CONTRACT, spec_revision=2)
    raw["entities"][0]["fields"].append({"name": "comment", "type": "text"})
    after = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    diffs = {d.path: d for d in diff_projects(before, after)}
    screen = diffs["src/screens/AdjustmentRulesScreen.tsx"]
    assert screen.status == "modified"
    added = [
        line[1:].strip() for line in screen.unified.splitlines() if line.startswith("+") and not line.startswith("+++")
    ]
    assert '<TableHeaderCell>{"Comment"}</TableHeaderCell>' in added
    assert screen.additions == 4  # new column header and row cell, plus the revision in the header lines
    assert "package.json" not in diffs
    assert diff_projects(before, before) == []


def test_naming_helpers() -> None:
    assert pascal("adjustment-rules") == "AdjustmentRules"
    assert package_name("Finance Operations") == "finance-operations-app"
    assert package_name("123") == "generated-app"


def test_allowlist_matches_the_workspace_preview() -> None:
    source = (ROOT / "apps" / "workspace-web" / "src" / "design" / "RenderTree.tsx").read_text(encoding="utf-8")
    block = source.split("export const REGISTRY", 1)[1].split("\n};", 1)[0]
    entry = re.compile(r'\n  "?([A-Za-z0-9]+)"?: \{\s*render: [^,]+,\s*props: (TYPOGRAPHY|\{.*?\})\s*,?\s*\}', re.S)
    found: dict[str, set[str]] = {}
    for match in entry.finditer(block):
        props = match.group(2)
        found[match.group(1)] = {"as"} if props == "TYPOGRAPHY" else set(re.findall(r'"?([a-zA-Z][\w-]*)"?:', props))
    assert found == {name: set(props) for name, props in ALLOWED.items()}


def test_navigation_and_validation_behaviour(raw: dict[str, Any]) -> None:
    raw["screens"], raw["navigation"] = [], []
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    listing = project.files["src/screens/AdjustmentListScreen.tsx"]
    assert 'onClick={() => navigate("/adjustment/new")}' in listing
    assert "const navigate = useNavigate();" in listing
    form = project.files["src/screens/AdjustmentFormScreen.tsx"]
    assert "noValidate onSubmit={form1.onSubmit}" in form
    # Money accepts decimals: step="any" (a plain number input would reject 125.50).
    assert (
        '<Input name={"amount"} required step={"any"} type={"number"} defaultValue={fieldValue(editing1, "amount")} />'
        in form
    )
    assert 'validationMessage={form1.errors["amount"]}' in form
    assert 'onClick={() => navigate("/adjustment")}>{"Cancel"}' in form
    labels = '{ "amount": "Amount", "kind": "Kind", "transaction": "Transaction" }'
    assert f"const FORM1_LABELS: Record<string, string> = {labels};" in form
    assert "navigateTo" not in form
    assert "useFormState" in project.files["src/forms.ts"]


def test_spec_validation_rules_become_native_constraints(raw: dict[str, Any]) -> None:
    raw["screens"][0]["components"] = [{"id": "edit", "kind": "form"}]
    raw["screens"][0]["fields"] = [
        {
            "name": "reference",
            "label": "Reference",
            "type": "string",
            "validation": [
                {"kind": "required"},
                {"kind": "max-length", "value": 12},
                {"kind": "pattern", "value": "[A-Z]{3}-[0-9]+"},
            ],
        },
        {"name": "count", "label": "Count", "type": "integer", "validation": [{"kind": "min", "value": 1}]},
    ]
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    screen = project.files["src/screens/AdjustmentRulesScreen.tsx"]
    assert '<Input maxLength={12} name={"reference"} pattern={"[A-Z]{3}-[0-9]+"} required type={"text"} />' in screen
    assert '<Input min={"1"} name={"count"} type={"number"} />' in screen


def test_tables_forms_and_references_are_bound_to_entity_stores(raw: dict[str, Any]) -> None:
    raw["screens"], raw["navigation"] = [], []
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    listing = project.files["src/screens/AdjustmentListScreen.tsx"]
    assert 'const rows1 = useEntityList(stores["adjustment"]);' in listing
    assert '<TableCell>{formatValue(row["amount"])}</TableCell>' in listing
    assert '<TableCell>{displayRef("transaction", row["transaction"])}</TableCell>' in listing
    assert '{"No adjustment records yet."}' in listing
    form = project.files["src/screens/AdjustmentFormScreen.tsx"]
    assert 'const options2 = useEntityList(stores["transaction"]);' in form
    assert '{displayName("transaction", record)}' in form
    save = 'save: async (data) => { await saveRecord("adjustment", data, editing1?.id); navigate("/adjustment"); }'
    assert f"useFormState({{ {save} }})" in form
    assert "<MessageBarTitle>Saved</MessageBarTitle>" in form
    entities = project.files["src/data/entities.ts"]
    assert '  "amount": number;' in entities
    assert '  "risk-score": number | null;' in entities
    assert '"transaction": { "risk-score": "number" },' in entities


def test_openapi_contract_describes_the_entities(raw: dict[str, Any]) -> None:
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    api = json.loads(project.files["api/openapi.json"])
    assert api["openapi"] == "3.1.0"
    assert set(api["paths"]) == {"/adjustment", "/adjustment/{id}", "/transaction", "/transaction/{id}"}
    schema = api["components"]["schemas"]["Adjustment"]
    assert schema["required"] == ["id", "amount", "kind"]
    assert schema["properties"]["kind"]["enum"] == ["accrual", "reclass", "write-off"]
    assert schema["properties"]["transaction"] == {
        "anyOf": [{"type": "string", "description": "Id of a transaction record."}, {"type": "null"}]
    }


def test_spec_without_entities_still_generates_a_data_module(spec: ApplicationSpec) -> None:
    bare = spec.model_copy(update={"entities": [], "screens": [], "navigation": []})
    project = generate_project(bare, CONTRACT, spec_revision=1)
    assert project.files["src/data/entities.ts"].endswith("export const stores = {};\n")
    assert json.loads(project.files["api/openapi.json"])["paths"] == {}


def test_lists_offer_edit_and_confirmed_delete(raw: dict[str, Any]) -> None:
    raw["screens"], raw["navigation"] = [], []
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    listing = project.files["src/screens/AdjustmentListScreen.tsx"]
    assert '<TableHeaderCell>{"Actions"}</TableHeaderCell>' in listing
    assert "<TableCell colSpan={4}>" in listing
    assert 'aria-label={`Edit ${displayName("adjustment", row)}`}' in listing
    assert 'navigate(`${"/adjustment/new"}?id=${encodeURIComponent(row.id)}`)' in listing
    assert (
        '<ConfirmDelete name={displayName("adjustment", row)} onConfirm={() => deleteRecord("adjustment", row.id)} />'
        in listing
    )
    assert 'import { ConfirmDelete } from "../components/ConfirmDelete";' in listing
    # The reference column subscribes to the referenced store, so names appear once it loads.
    assert 'useEntityList(stores["transaction"]);' in listing
    dialog = project.files["src/components/ConfirmDelete.tsx"]
    assert "<DialogTrigger disableButtonEnhancement>" in dialog
    assert "aria-label={`Delete ${name}`}" in dialog


def test_bound_forms_edit_the_record_named_in_the_url(raw: dict[str, Any]) -> None:
    raw["screens"], raw["navigation"] = [], []
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    form = project.files["src/screens/AdjustmentFormScreen.tsx"]
    assert 'const editing1 = useRecord(stores["adjustment"], searchParams.get("id"));' in form
    assert "const [searchParams] = useSearchParams();" in form
    assert 'key={editing1?.id ?? "new"}' in form
    assert 'defaultValue={fieldValue(editing1, "kind")}' in form
    # The reference select remounts when its options load, so the edited value can be selected.
    assert 'defaultValue={fieldValue(editing1, "transaction")} key={options2.length}>' in form
    assert "<MessageBarTitle>Could not save</MessageBarTitle>" in form


def test_stores_switch_to_http_when_an_api_url_is_configured(raw: dict[str, Any]) -> None:
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    entities = project.files["src/data/entities.ts"]
    assert "import.meta.env.VITE_DATA_API_URL" in entities
    assert '"adjustment": storeFor<Adjustment>("adjustment"),' in entities
    store = project.files["src/data/store.ts"]
    assert "export function createHttpStore<T extends Entity>(baseUrl: string, collection: string)" in store
    assert 'method: "PUT"' in store
    assert 'method: "DELETE"' in store
    assert json.loads(project.files["tsconfig.json"])["compilerOptions"]["types"] == ["vite/client"]
    api = json.loads(project.files["api/openapi.json"])
    item = api["paths"]["/adjustment/{id}"]
    assert set(item) == {"get", "put", "delete"}
    assert item["delete"]["responses"]["204"]["description"] == "Deleted"


def test_brand_themes_change_the_fluent_theme_only(spec: ApplicationSpec) -> None:
    from design_system import BrandTheme

    default = generate_project(spec, CONTRACT, spec_revision=2)
    assert "export const appTheme: Theme = webLightTheme;" in default.files["src/theme.ts"]
    assert "<FluentProvider theme={appTheme}>" in default.files["src/App.tsx"]
    theme = BrandTheme(
        id="acme", name='Acme "Red"', base="fluent2", brand_color="#8A1538", font_family="Inter, sans-serif"
    )
    branded = generate_project(spec, CONTRACT, spec_revision=2, theme=theme)
    source = branded.files["src/theme.ts"]
    assert '  80: "#8a1538",' in source
    assert source.count(': "#') == 16  # sixteen BrandVariants
    assert '  fontFamilyBase: "Inter, sans-serif",' in source
    assert 'Organization brand theme "Acme \\"Red\\"" ("org-acme") on Fluent 2.' in source
    assert branded.design_system == "org-acme (fluent2@1.0.0)"
    assert json.loads(branded.files[MANIFEST])["design_system"] == "org-acme (fluent2@1.0.0)"
    changed = {p for p in default.files if default.files[p] != branded.files.get(p)}
    assert changed == {"src/theme.ts", MANIFEST}
