from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

from appspec import load_spec
from codegen_angular import ATTRIBUTES, ELEMENTS, ScreenBuilder, generate_project, literal, toolchain
from codegen_angular.generate import _list_routes
from codegen_angular.template import Element, interpolate
from codegen_react import MANIFEST, GenerationBlocked, GenerationError
from design_system import derive_document, get_contract
from design_system.ir import Form, Heading, Screen, ScreenSource

ROOT = Path(__file__).resolve().parents[3]
EXAMPLE = ROOT / "packages" / "application-spec" / "examples" / "finance-operations.json"
CONTRACT = get_contract("material3")
assert CONTRACT is not None


@pytest.fixture
def raw() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(EXAMPLE.read_text(encoding="utf-8"))
    return data


def entities_only(raw: dict[str, Any]) -> dict[str, Any]:
    raw["screens"], raw["navigation"] = [], []
    return raw


def templates(files: dict[str, str]) -> dict[str, str]:
    out = {}
    for path, content in files.items():
        if path.startswith("src/app/screens/"):
            out[path] = content.split("template: `", 1)[1].split("\n  `,", 1)[0]
    return out


def test_project_layout_provenance_and_determinism(raw: dict[str, Any]) -> None:
    spec = load_spec(raw)
    project = generate_project(spec, CONTRACT, spec_revision=4)
    assert project.generator == "codegen-angular@0.1.0"
    assert project.design_system == "material3@1.0.0"
    assert set(project.files) == {
        ".gitignore",
        "README.md",
        "angular.json",
        "package.json",
        "tsconfig.json",
        "src/index.html",
        "src/main.ts",
        "src/styles.css",
        "src/app/app.ts",
        "src/app/app.routes.ts",
        "src/app/forms.ts",
        "src/app/data/entities.ts",
        "src/app/data/store.ts",
        "src/app/screens/adjustment-rules-screen.ts",
        MANIFEST,
    }
    screen = project.files["src/app/screens/adjustment-rules-screen.ts"]
    assert screen.startswith(
        "// Generated by codegen-angular@0.1.0 from spec r4 (UI IR v1, design system material3@1.0.0)."
    )
    assert "export class AdjustmentRulesScreen {" in screen
    manifest = json.loads(project.files[MANIFEST])
    assert manifest["library"] == "@angular/material@22.2.2"
    assert manifest["files"]["src/main.ts"] == project.sha256("src/main.ts")
    assert generate_project(spec, CONTRACT, spec_revision=4).files == project.files
    main = project.files["src/main.ts"]
    assert "provideZonelessChangeDetection()" in main
    angular = json.loads(project.files["angular.json"])
    build = angular["projects"]["app"]["architect"]["build"]
    assert build["builder"] == "@angular/build:application"
    assert build["options"]["styles"][0] == "@angular/material/prebuilt-themes/azure-blue.css"
    assert angular["cli"]["analytics"] is False
    tsconfig = json.loads(project.files["tsconfig.json"])
    assert tsconfig["angularCompilerOptions"]["strictTemplates"] is True


def test_dependencies_are_pinned_exactly_to_the_angular_toolchain_lockfile() -> None:
    folder = ROOT / "toolchains" / "angular"
    tools = toolchain()
    package = json.loads((folder / "package.json").read_text(encoding="utf-8"))
    lock = json.loads((folder / "package-lock.json").read_text(encoding="utf-8"))["packages"]
    for group in ("dependencies", "devDependencies"):
        assert package[group] == tools[group], group
        for name, version in tools[group].items():
            assert re.fullmatch(r"\d+\.\d+\.\d+", version), f"{name} must be pinned exactly"
            assert lock[f"node_modules/{name}"]["version"] == version, name
    assert tools["dependencies"]["@angular/material"] == CONTRACT.library.version


def test_hostile_spec_text_never_reaches_templates(raw: dict[str, Any]) -> None:
    evil = 'Pwn`${alert(1)}`</script><b>{{ constructor.constructor("x")() }}</b> \u2028 é'
    raw["metadata"]["name"] = evil
    raw["screens"][0]["name"] = evil
    raw["screens"][0]["components"][0]["label"] = evil
    raw["entities"][0]["name"] = evil
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=2)
    for path, template in templates(project.files).items():
        assert "Pwn" not in template, path
        assert "{{ constructor" not in template, path
    for path, content in project.files.items():
        if path.endswith(".ts"):
            outside = content.replace(literal(evil), '""')
            assert "Pwn" not in outside, path
            assert "\u2028" not in content, path
            assert "`${" not in content.replace("`${Date.now()", "").replace("`generated-app:${", ""), path
    assert "&lt;/script&gt;" in project.files["src/index.html"]


def test_templates_use_only_allowlisted_markup_and_contract_components(raw: dict[str, Any]) -> None:
    spec = load_spec(entities_only(raw))
    document = derive_document(spec)
    routes = {s.id: s.route for s in document.screens}
    material_names = " ".join(c for m in CONTRACT.mappings.values() for c in m.components)
    for index, screen in enumerate(document.screens):
        builder = ScreenBuilder(screen, index, spec, _list_routes(document), routes)
        builder.file("// header\n")
        tags, attrs = builder.used()
        assert tags <= ELEMENTS
        assert attrs <= set(ATTRIBUTES)
        for tag in tags:
            if tag.startswith("mat-"):
                assert tag in material_names, tag
        for attr in attrs:
            if attr.startswith(("mat", "*mat")) and attr not in ("matColumnDef",):
                assert attr.lstrip("*") in material_names or attr.lstrip("*").startswith(
                    ("matHeader", "matCell", "matRow", "matNoDataRow")
                ), attr


def test_template_builder_refuses_anything_off_the_allowlist() -> None:
    with pytest.raises(GenerationError, match="element 'script'"):
        Element("script")
    with pytest.raises(GenerationError, match="attribute 'onclick'"):
        Element("button", [("onclick", "alert(1)")])
    with pytest.raises(GenerationError, match="unsafe expression"):
        Element("button", [("(click)", "go('x')")])
    with pytest.raises(GenerationError, match="not allowed for 'class'"):
        Element("div", [("class", "x onmouseover")])
    with pytest.raises(GenerationError, match="unsafe interpolation"):
        interpolate("t.k0 }}<script>")
    with pytest.raises(GenerationError, match="unsafe control-flow"):
        Element("div", [], ["<b>raw text</b>"])


def test_entity_screens_bind_tables_and_forms_to_stores(raw: dict[str, Any]) -> None:
    project = generate_project(load_spec(entities_only(raw)), CONTRACT, spec_revision=3)
    listing = project.files["src/app/screens/adjustment-list-screen.ts"]
    assert 'protected readonly rows1 = stores["adjustment"].list;' in listing
    assert '<table mat-table [dataSource]="rows1()" [attr.aria-label]="t.k8">' in listing
    assert '[["amount"], ["kind"], ["transaction", "transaction"]]' in listing
    assert "*matNoDataRow" in listing
    form = project.files["src/app/screens/adjustment-form-screen.ts"]
    assert "c0: new FormControl<number | null>(null, { validators: [Validators.required] })," in form
    assert '<input matInput formControlName="c0" required type="number" step="any" />' in form
    assert '<select matNativeControl formControlName="c1" required>' in form
    assert 'protected readonly choices1x2 = stores["transaction"].list;' in form
    assert 'saveRecord("adjustment", { ["amount"]: raw.c0, ["kind"]: raw.c1, ["transaction"]: raw.c2 });' in form
    assert 'void this.router.navigateByUrl("/adjustment");' in form
    routes = project.files["src/app/app.routes.ts"]
    assert '{ path: "adjustment/new", component: AdjustmentFormScreen, title: "New adjustment" },' in routes
    assert '{ path: "", pathMatch: "full", redirectTo: "adjustment" },' in routes
    # Row actions are not generated for Angular yet; the gap is reported, not hidden.
    assert "angular-row-actions" in {w.code for w in project.warnings}
    entities = project.files["src/app/data/entities.ts"]
    assert '  "risk-score": number | null;' in entities


def test_spec_rules_become_validators(raw: dict[str, Any]) -> None:
    raw["screens"][0]["components"] = [{"id": "edit", "kind": "form"}]
    raw["screens"][0]["fields"] = [
        {
            "name": "reference",
            "label": "Reference",
            "type": "string",
            "validation": [
                {"kind": "required"},
                {"kind": "max-length", "value": 12},
                {"kind": "pattern", "value": "[A-Z]{3}-[0-9]+"},
            ],
        },
        {"name": "count", "label": "Count", "type": "integer", "validation": [{"kind": "min", "value": 1}]},
    ]
    project = generate_project(load_spec(raw), CONTRACT, spec_revision=3)
    screen = project.files["src/app/screens/adjustment-rules-screen.ts"]
    assert 'Validators.required, Validators.maxLength(12), Validators.pattern("[A-Z]{3}-[0-9]+")' in screen
    assert "Validators.min(1)" in screen
    assert "this.saved1.set(true);" in screen  # an unbound form validates but does not save


def test_ir_errors_block_generation_and_react_contracts_are_refused(raw: dict[str, Any]) -> None:
    spec = load_spec(raw)
    broken = derive_document(spec).model_copy(
        update={
            "screens": [
                Screen(
                    id="s",
                    title="S",
                    route="/s",
                    source=ScreenSource(kind="spec-screen", ref="s"),
                    body=[Heading(id="h", text="S", level=1), Form(id="f", label="F")],
                )
            ]
        }
    )
    with pytest.raises(GenerationBlocked):
        generate_project(spec, CONTRACT, document=broken)
    fluent = get_contract("fluent2")
    assert fluent is not None
    with pytest.raises(GenerationError, match="not an Angular design system"):
        generate_project(spec, fluent)
