"""Upgrade a hand-edited generated project to a newer spec revision, keeping the edits (Milestone 5).

The user uploads the project zip they have been editing. Its ``workspace-manifest.json`` says
which revision and generator version produced it. When that generator version is the current
one, the original generated project is reproduced exactly (generation is deterministic) and
every file is merged three-way (``codegen_react.merge``). Otherwise edited files are kept and
the regenerated version is written beside them.

The upload is untrusted: it is read with the build runner's bounded, traversal-safe zip
reader, never executed, never stored. The result is returned to the caller only.
"""

from __future__ import annotations

import base64
import io
import json
import uuid
import zipfile
from typing import Any

from sqlalchemy.orm import Session

from build_runner import ProjectRejected, read_archive
from codegen_react import MANIFEST, merge_projects, package_name

from . import code, service
from .auth import Principal
from .errors import AppError, FieldError
from .schemas import UpgradeFile, UpgradeResult

_ZIP_TIME = (2026, 1, 1, 0, 0, 0)


class UploadRejected(AppError):
    status, code, title = 422, "upload-rejected", "The uploaded project cannot be upgraded"


def _manifest(contents: dict[str, bytes]) -> dict[str, Any]:
    raw = contents.get(MANIFEST)
    if raw is None:
        raise UploadRejected(
            f"The archive has no {MANIFEST}; only projects generated by the workspace can be upgraded."
        )
    try:
        manifest = json.loads(raw)
        if not isinstance(manifest.get("files"), dict) or not isinstance(manifest.get("spec_revision"), int):
            raise ValueError
    except ValueError as exc:
        raise UploadRejected(f"{MANIFEST} is not valid.") from exc
    return manifest  # type: ignore[no-any-return]


def run(
    session: Session, principal: Principal, project_id: uuid.UUID, data: bytes, to_revision: int | None
) -> UpgradeResult:
    project = service.find_project(session, principal, project_id)
    try:
        _, contents = read_archive(data)
    except ProjectRejected as exc:
        raise UploadRejected(str(exc), errors=[FieldError(path="/", message=str(exc), code=exc.code)]) from exc
    manifest = _manifest(contents)
    from_revision: int = manifest["spec_revision"]
    from_generator = str(manifest.get("generator", "unknown"))
    base_hashes = {str(k): str(v) for k, v in manifest["files"].items()}

    number, new = code.project_at(session, principal, project_id, to_revision)
    base_files: dict[str, str] | None = None
    if from_generator == new.generator and 1 <= from_revision <= project.current_revision:
        try:
            _, base = code.project_at(session, principal, project_id, from_revision)
            base_files = dict(base.files)
        except AppError:
            base_files = None  # that revision no longer generates; fall back to side-by-side

    text: dict[str, str] = {}
    binary: dict[str, bytes] = {}
    for path, raw in contents.items():
        try:
            text[path] = raw.decode("utf-8")
        except UnicodeDecodeError:
            binary[path] = raw
    merged = merge_projects(
        text,
        dict(new.files),
        base_files,
        base_hashes,
        label=f"regenerated r{number}",
        generated_only=frozenset({MANIFEST}),
    )
    outcomes = [UpgradeFile(path=o.path, status=o.status, conflicts=o.conflicts, note=o.note) for o in merged.outcomes]
    for path in sorted(binary):
        if path in new.files:  # a generated (text) path replaced by binary content: keep the user's, flag it
            outcomes.append(UpgradeFile(path=path, status="conflict", conflicts=1, note="binary file in your copy"))
        else:
            outcomes.append(UpgradeFile(path=path, status="user-file", conflicts=0, note=None))

    root = f"{package_name(project.name)}-r{number}"
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        files: dict[str, bytes] = {p: c.encode("utf-8") for p, c in merged.files.items()}
        files.update(binary)
        for path in sorted(files):
            info = zipfile.ZipInfo(f"{root}/{path}", date_time=_ZIP_TIME)
            info.external_attr = 0o644 << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, files[path])

    conflicts = merged.conflicts + sum(1 for path in binary if path in new.files)
    service.audit(
        session,
        principal,
        project.id,
        "code.upgraded",
        from_revision=from_revision,
        to_revision=number,
        conflicts=conflicts,
        base_reproduced=base_files is not None,
    )
    session.commit()
    return UpgradeResult(
        from_revision=from_revision,
        from_generator=from_generator,
        to_revision=number,
        generator=new.generator,
        base_reproduced=base_files is not None,
        conflicts=conflicts,
        files=sorted(outcomes, key=lambda o: o.path),
        filename=f"{root}.zip",
        archive_base64=base64.b64encode(buffer.getvalue()).decode("ascii"),
    )
