"""Generate a complete Angular + Material 3 project from a spec revision (ADR-0017).

Same guarantees as the React generator (ADR-0014):
- deterministic output, with provenance headers and a SHA-256 manifest;
- exact dependency pins;
- generation refused while the UI IR has errors;
- spec text only ever as escaped string literals.

The project uses standalone components, signals, zoneless change detection, typed reactive
forms with validators from the spec rules, and Angular Material 3 components.
"""

from __future__ import annotations

import html
import json
from importlib import resources
from typing import Any

from appspec import ApplicationSpec
from appspec.model import FieldType
from codegen_react import MANIFEST, GeneratedProject, GenerationBlocked, GenerationError, package_name, pascal
from codegen_react.generate import design_system_label
from design_system import BrandTheme, DesignSystemContract, UiDocument, brand_ramp, derive_document, validate_document
from design_system.ir import (
    Action,
    Form,
    FormField,
    Heading,
    Message,
    Node,
    Placeholder,
    Screen,
    Section,
    Stat,
    Table,
    Text,
    Toolbar,
)
from design_system.validate import UiIssue

from .template import Element, control_flow, identifier, interpolate, render, tags_and_attributes

GENERATOR = "codegen-angular"
GENERATOR_VERSION = "0.1.0"
_HEADINGS = {1: "h1", 2: "h2", 3: "h3", 4: "h4"}
_NUMERIC = {FieldType.INTEGER, FieldType.DECIMAL, FieldType.MONEY}


def toolchain() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(resources.files(__package__).joinpath("toolchain.json").read_text("utf-8"))
    return data


def literal(value: Any) -> str:
    """A TypeScript literal for any JSON value: ASCII-escaped, safe inside a template string or a file."""
    text = json.dumps(value, ensure_ascii=True)
    return text.replace("`", "\\u0060").replace("${", "$\\u007b").replace("</", "<\\/")


def _header(spec_revision: int | None, contract: DesignSystemContract) -> str:
    revision = f"r{spec_revision}" if spec_revision is not None else "an unsaved spec"
    return (
        f"// Generated by {GENERATOR}@{GENERATOR_VERSION} from spec {revision} "
        f"(UI IR v1, design system {contract.id}@{contract.version}).\n"
        "// You may edit this file: upgrading in the workspace merges your edits with the regenerated code.\n"
    )


def _kind(field_type: FieldType) -> str:
    if field_type in _NUMERIC:
        return "number"
    if field_type is FieldType.BOOLEAN:
        return "boolean"
    return "string"


def _ts_type(field_type: FieldType) -> str:
    return {"number": "number", "boolean": "boolean", "string": "string"}[_kind(field_type)]


def _number(value: object) -> int | float | None:
    """A finite number from a rule value (numbers arrive as numbers or numeric strings)."""
    if isinstance(value, bool) or value is None:
        return None
    try:
        number = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None
    if number != number or number in (float("inf"), float("-inf")):
        return None
    return int(number) if number.is_integer() else number


def type_name(entity_id: str) -> str:
    name = pascal(entity_id)
    return name if name[:1].isalpha() else f"Entity{name}"


class ScreenBuilder:
    """Builds one standalone screen component from an IR screen."""

    def __init__(
        self, screen: Screen, index: int, spec: ApplicationSpec, list_routes: dict[str, str], routes: dict[str, str]
    ) -> None:
        self.screen = screen
        self.index = index
        self.spec = spec
        self.entities = {e.id: e for e in spec.entities}
        self.list_routes = list_routes
        self.routes = routes
        self.texts: list[str] = []
        self.members: list[str] = []
        self.methods: list[str] = []
        self.imports: dict[str, set[str]] = {}
        self.data_imports: set[str] = set()
        self.form_count = 0
        self.table_count = 0
        self.route_keys: dict[str, str] = {}
        self.uses_router = False
        self.uses_forms_helpers = False
        self.uses_files = False
        self.warnings: list[UiIssue] = []
        self.body: list[Element | str] = []

    # ------------------------------------------------------------------ helpers
    def text(self, value: str) -> str:
        self.texts.append(value)
        return f"t.k{len(self.texts) - 1}"

    def need(self, module: str, *names: str) -> None:
        self.imports.setdefault(module, set()).update(names)

    def route(self, path: str) -> str:
        if path not in self.route_keys:
            self.route_keys[path] = f"r{len(self.route_keys)}"
        self.uses_router = True
        return f"r.{self.route_keys[path]}"

    def button(self, action: Action, *, in_form: bool, form_var: str | None = None) -> Element:
        self.need("@angular/material/button", "MatButtonModule")
        variant = "mat-flat-button" if action.intent in ("primary", "danger") else "mat-stroked-button"
        attrs: list[tuple[str, str | None]] = [(variant, None)]
        if action.intent == "danger":
            attrs.append(("class", "danger"))
        if in_form and action.action == "submit":
            attrs.append(("type", "submit"))
        else:
            attrs.append(("type", "button"))
            target = self.routes.get(action.target_screen or "")
            if action.action in ("navigate", "cancel") and target:
                attrs.append(("(click)", f"go({self.route(target)})"))
        return Element("button", attrs, [interpolate(self.text(action.label))])

    # ------------------------------------------------------------------ nodes
    def nodes(self, nodes: list[Node]) -> list[Element | str]:
        out: list[Element | str] = []
        for node in nodes:
            out.extend(self.node(node))
        return out

    def node(self, node: Node) -> list[Element | str]:
        if isinstance(node, Heading):
            return [Element(_HEADINGS[node.level], [], [interpolate(self.text(node.text))])]
        if isinstance(node, Text):
            attrs: list[tuple[str, str | None]] = [("class", "subtle")] if node.tone == "subtle" else []
            return [Element("p", attrs, [interpolate(self.text(node.text))])]
        if isinstance(node, Section):
            attrs = [("[attr.aria-label]", self.text(node.title))] if node.title else []
            return [Element("section", attrs, self.nodes(node.children))]
        if isinstance(node, Form):
            return self.form(node)
        if isinstance(node, Table):
            return self.table(node)
        if isinstance(node, Stat):
            label = self.text(node.label)
            return [
                Element(
                    "div",
                    [("class", "stat"), ("role", "group"), ("[attr.aria-label]", label)],
                    [
                        Element("p", [("class", "stat-label")], [interpolate(label)]),
                        Element("p", [("class", "stat-value")], [interpolate(self.text(node.value_hint))]),
                    ],
                )
            ]
        if isinstance(node, Message):
            children: list[Element | str] = [Element("strong", [], [interpolate(self.text(node.title))])]
            if node.text:
                children.append(Element("span", [], [interpolate(self.text(" " + node.text))]))
            return [Element("div", [("class", f"message message-{node.intent}"), ("role", "status")], children)]
        if isinstance(node, Toolbar):
            buttons: list[Element | str] = [self.button(a, in_form=False) for a in node.actions]
            toolbar_attrs: list[tuple[str, str | None]] = [
                ("class", "toolbar"),
                ("role", "toolbar"),
                ("[attr.aria-label]", self.text(node.label)),
            ]
            return [Element("div", toolbar_attrs, buttons)]
        if isinstance(node, Placeholder):
            label = f" ({node.label})" if node.label else ""
            message = f"Not supported yet: {node.requested_kind}{label}. {node.reason}"
            return [Element("div", [("class", "unsupported")], [interpolate(self.text(message))])]
        raise GenerationError(f"unhandled IR node {type(node).__name__}")

    # ------------------------------------------------------------------ forms
    def _validators(self, field: FormField) -> list[str]:
        out: list[str] = []
        if field.required:
            out.append("Validators.requiredTrue" if field.input == "checkbox" else "Validators.required")
        for rule in field.validation:
            value = rule.value
            if rule.kind == "required" and "Validators.required" not in out and field.input != "checkbox":
                out.append("Validators.required")
            elif rule.kind in ("min", "max") and field.input == "number" and _number(value) is not None:
                out.append(f"Validators.{rule.kind}({literal(_number(value))})")
            elif rule.kind in ("min-length", "max-length") and field.input in ("text", "textarea"):
                if isinstance(value, int | float) and float(value).is_integer() and 0 <= value <= 100_000:
                    name = "minLength" if rule.kind == "min-length" else "maxLength"
                    out.append(f"Validators.{name}({int(value)})")
            elif rule.kind == "pattern" and field.input == "text" and isinstance(value, str) and 0 < len(value) <= 200:
                out.append(f"Validators.pattern({literal(value)})")
        return out

    def form(self, form: Form) -> list[Element | str]:
        self.form_count += 1
        n = self.form_count
        fvar = identifier(f"form{n}")
        self.need("@angular/forms", "ReactiveFormsModule", "FormGroup", "FormControl")
        self.uses_forms_helpers = True
        entity = self.entities.get(form.entity_id or "")
        controls: list[str] = []
        labels: dict[str, str] = {}
        children: list[Element | str] = []
        has_files = any(f.input == "file" for f in form.fields)
        for i, field in enumerate(form.fields):
            cname = identifier(f"c{i}")
            labels[cname] = field.label
            validators = self._validators(field)
            if validators:
                self.need("@angular/forms", "Validators")
            vlist = f"[{', '.join(validators)}]"
            if field.input == "checkbox":
                controls.append(
                    f"    {cname}: new FormControl<boolean>(false, {{ nonNullable: true, validators: {vlist} }}),"
                )
                self.need("@angular/material/checkbox", "MatCheckboxModule")
                children.append(
                    Element("mat-checkbox", [("formControlName", cname)], [interpolate(self.text(field.label))])
                )
                continue
            if field.input == "file":
                self.uses_files = True
                children.append(
                    Element(
                        "label",
                        [("class", "file-field")],
                        [
                            Element("span", [], [interpolate(self.text(field.label))]),
                            Element("input", [("type", "file"), ("(change)", f"pickFile(files{n}, {i}, $event)")]),
                        ],
                    )
                )
                continue
            if field.input == "number":
                controls.append(f"    {cname}: new FormControl<number | null>(null, {{ validators: {vlist} }}),")
            else:
                controls.append(
                    f'    {cname}: new FormControl<string>("", {{ nonNullable: true, validators: {vlist} }}),'
                )
            self.need("@angular/material/form-field", "MatFormFieldModule")
            inner: list[Element | str] = [Element("mat-label", [], [interpolate(self.text(field.label))])]
            control_attrs: list[tuple[str, str | None]] = [("formControlName", cname)]
            if field.required:
                control_attrs.append(("required", None))
            if field.input == "select":
                self.need("@angular/material/input", "MatInputModule")
                options: list[Element | str] = [Element("option", [("value", "")], [interpolate(self.text("Select…"))])]
                if field.options_from_entity and field.options_from_entity in self.entities:
                    self.data_imports |= {"stores", "displayName"}
                    ovar = identifier(f"choices{n}x{i}")
                    self.members.append(
                        f"  protected readonly {ovar} = stores[{literal(field.options_from_entity)}].list;"
                    )
                    self.members.append(
                        f"  protected readonly {ovar}Label = (record: Entity): string => "
                        f"displayName({literal(field.options_from_entity)}, record);"
                    )
                    self.data_imports.add("Entity")
                    options += [
                        control_flow(f"@for (record of {ovar}(); track record.id) {{"),
                        Element("option", [("[value]", "record.id")], [interpolate(f"{ovar}Label(record)")]),
                        control_flow("}"),
                    ]
                else:
                    ovar = identifier(f"options{n}x{i}")
                    self.members.append(f"  protected readonly {ovar} = {literal(list(field.options))};")
                    options += [
                        control_flow(f"@for (option of {ovar}; track option) {{"),
                        Element("option", [("[value]", "option")], [interpolate("option")]),
                        control_flow("}"),
                    ]
                inner.append(Element("select", [("matNativeControl", None), *control_attrs], options))
            else:
                self.need("@angular/material/input", "MatInputModule")
                tag = "textarea" if field.input == "textarea" else "input"
                attrs: list[tuple[str, str | None]] = [("matInput", None), *control_attrs]
                if tag == "input":
                    input_type = {"text": "text", "number": "number", "date": "date", "datetime": "datetime-local"}
                    attrs.append(("type", input_type.get(field.input, "text")))
                    if field.input == "number" and field.number_kind == "decimal":
                        attrs.append(("step", "any"))
                inner.append(Element(tag, attrs))
            if field.help_text:
                inner.append(Element("mat-hint", [], [interpolate(self.text(field.help_text))]))
            inner.append(Element("mat-error", [], [interpolate(f"errorText({fvar}.controls.{cname})")]))
            children.append(Element("mat-form-field", [("appearance", "outline")], inner))

        if form.actions:
            action_buttons: list[Element | str] = [self.button(a, in_form=True) for a in form.actions]
            children.append(Element("div", [("class", "actions")], action_buttons))
        invalid, saved = identifier(f"invalid{n}"), identifier(f"saved{n}")
        children += [
            control_flow(f"@if ({invalid}().length > 0) {{"),
            Element(
                "div",
                [("class", "message message-error"), ("role", "alert")],
                [
                    Element("strong", [], [interpolate(f"fixText({invalid}().length)")]),
                    Element("span", [], [interpolate(f"joinLabels({invalid}())")]),
                ],
            ),
            control_flow("}"),
            control_flow(f"@if ({saved}()) {{"),
            Element(
                "div",
                [("class", "message message-success"), ("role", "status")],
                [
                    Element("strong", [], [interpolate(self.text("Validated"))]),
                    Element("span", [], [interpolate(self.text(" Saving is not connected to a backend yet."))]),
                ],
            ),
            control_flow("}"),
        ]
        self.need("@angular/core", "signal")
        self.members += [
            f"  protected readonly {fvar} = new FormGroup({{",
            *controls,
            "  });",
            f"  protected readonly {invalid} = signal<readonly string[]>([]);",
            f"  protected readonly {saved} = signal(false);",
            f"  private readonly labels{n}: Record<string, string> = {literal(labels)};",
        ]
        if has_files:
            self.members.append(f"  protected readonly files{n}: Record<number, string | null> = {{}};")
        save_lines = [f"    this.{saved}.set(true);"]
        if entity is not None:
            self.data_imports.add("saveRecord")
            entries = [
                f"[{literal(f.name)}]: this.files{n}[{i}] ?? null"
                if f.input == "file"
                else f"[{literal(f.name)}]: raw.c{i}"
                for i, f in enumerate(form.fields)
            ]
            record = ", ".join(entries)
            back = self.list_routes.get(entity.id)
            save_lines = [
                f"    const raw = this.{fvar}.getRawValue();",
                f"    saveRecord({literal(entity.id)}, {{ {record} }});",
            ]
            if back and back != self.screen.route:
                self.uses_router = True
                save_lines.append(f"    void this.router.navigateByUrl({literal(back)});")
            else:
                save_lines.append(f"    this.{saved}.set(true);")
        self.methods += [
            f"  protected submit{n}(): void {{",
            f"    this.{fvar}.markAllAsTouched();",
            f"    if (this.{fvar}.invalid) {{",
            f"      this.{invalid}.set(invalidLabels(this.{fvar}, this.labels{n}));",
            f"      this.{saved}.set(false);",
            "      return;",
            "    }",
            f"    this.{invalid}.set([]);",
            *save_lines,
            "  }",
        ]
        return [
            Element(
                "form",
                [("[formGroup]", fvar), ("(ngSubmit)", f"submit{n}()"), ("[attr.aria-label]", self.text(form.label))],
                children,
            )
        ]

    # ------------------------------------------------------------------ tables
    def table(self, table: Table) -> list[Element | str]:
        self.table_count += 1
        n = self.table_count
        self.need("@angular/material/table", "MatTableModule")
        rows, columns = identifier(f"rows{n}"), identifier(f"columns{n}")
        entity = self.entities.get(table.entity_id or "")
        if entity is not None:
            self.data_imports.add("stores")
            self.members.append(f"  protected readonly {rows} = stores[{literal(entity.id)}].list;")
        else:
            self.need("@angular/core", "signal")
            self.members.append(f"  protected readonly {rows} = signal<readonly Record<string, unknown>[]>([]);")
        if table.row_actions:
            self.warnings.append(
                UiIssue(
                    path=f"/screens/{self.index}",
                    code="angular-row-actions",
                    severity="warning",
                    message="Edit and delete row actions are not generated for Angular yet.",
                )
            )
        column_ids = [f"c{i}" for i in range(len(table.columns))]
        self.members.append(f"  protected readonly {columns} = {literal(column_ids)};")
        cells: list[list[str]] = []
        definitions: list[Element | str] = []
        for i, column in enumerate(table.columns):
            ref = None
            if entity is not None and column.type == "reference":
                field = next((f for f in entity.fields if f.name == column.key), None)
                ref = field.reference_entity_id if field is not None else None
            if ref is not None and ref in self.entities:
                cells.append([column.key, ref])
            else:
                cells.append([column.key])
            definitions.append(
                Element(
                    "ng-container",
                    [("matColumnDef", f"c{i}")],
                    [
                        Element(
                            "th",
                            [("mat-header-cell", None), ("*matHeaderCellDef", None)],
                            [interpolate(self.text(column.label))],
                        ),
                        Element(
                            "td", [("mat-cell", None), ("*matCellDef", "let row")], [interpolate(f"cell{n}(row, {i})")]
                        ),
                    ],
                )
            )
        self.data_imports |= {"formatValue", "displayRef"}
        self.members.append(f"  private readonly cells{n}: readonly (readonly string[])[] = {literal(cells)};")
        self.methods += [
            f"  protected cell{n}(row: Record<string, unknown>, index: number): string {{",
            f"    const [key, ref] = this.cells{n}[index] ?? [];",
            '    if (key === undefined) return "";',
            "    return ref ? displayRef(ref, row[key]) : formatValue(row[key]);",
            "  }",
        ]
        empty = self.text(table.empty_text)
        definitions += [
            Element("tr", [("mat-header-row", None), ("*matHeaderRowDef", columns)]),
            Element("tr", [("mat-row", None), ("*matRowDef", f"let row; columns: {columns}")]),
            Element(
                "tr",
                [("class", "mat-mdc-row"), ("*matNoDataRow", None)],
                [
                    Element(
                        "td",
                        [("class", "mat-mdc-cell empty"), ("[attr.colspan]", f"{columns}.length")],
                        [interpolate(empty)],
                    )
                ],
            ),
        ]
        return [
            Element(
                "table",
                [("mat-table", None), ("[dataSource]", f"{rows}()"), ("[attr.aria-label]", self.text(table.caption))],
                definitions,
            )
        ]

    # ------------------------------------------------------------------ file
    def file(self, header: str) -> tuple[str, str]:
        body = self.nodes(self.screen.body)
        self.body = body
        template = render(body, 2)
        joined = "\n".join(template)
        if "`" in joined or "${" in joined:
            raise GenerationError("template contains template-literal syntax")
        cls = pascal(self.screen.id)
        cls = (cls if cls[:1].isalpha() else f"Screen{cls}") + "Screen"
        imports = ["Component"]
        if self.uses_router:
            imports.append("inject")
        imports += sorted(self.imports.pop("@angular/core", set()))
        lines = [header.rstrip("\n"), "", f'import {{ {", ".join(sorted(set(imports)))} }} from "@angular/core";']
        if self.uses_router:
            lines.append('import { Router } from "@angular/router";')
        for module in sorted(self.imports):
            lines.append(f"import {{ {', '.join(sorted(self.imports[module]))} }} from {literal(module)};")
        data = sorted(self.data_imports - {"Entity"})
        if data or "Entity" in self.data_imports:
            names = data + (["type Entity"] if "Entity" in self.data_imports else [])
            lines.append(f'import {{ {", ".join(names)} }} from "../data/entities";')
        if self.uses_forms_helpers:
            helpers = ["errorText", "fixText", "invalidLabels", "joinLabels"] + (
                ["pickFile"] if self.uses_files else []
            )
            lines.append(f'import {{ {", ".join(helpers)} }} from "../forms";')
        texts = {f"k{i}": v for i, v in enumerate(self.texts)}
        lines += ["", f"const TEXT = {literal(texts)} as const;"]
        if self.route_keys:
            lines.append(f"const ROUTES = {literal({k: p for p, k in self.route_keys.items()})} as const;")
        component_imports = sorted(
            {name for module, names in self.imports.items() for name in names if name.endswith("Module")}
        )
        lines += [
            "",
            "@Component({",
            f"  selector: {literal(f'app-screen-{self.index}')},",
            f"  imports: [{', '.join(component_imports)}],",
            "  template: `",
            *template,
            "  `,",
            "})",
            f"export class {cls} {{",
            "  protected readonly t = TEXT;",
        ]
        if self.route_keys:
            lines.append("  protected readonly r = ROUTES;")
        if self.uses_router:
            lines.append("  private readonly router = inject(Router);")
        lines += self.members
        if self.uses_forms_helpers:
            lines += [
                "  protected readonly errorText = errorText;",
                "  protected readonly fixText = fixText;",
                "  protected readonly joinLabels = joinLabels;",
            ]
            if self.uses_files:
                lines.append("  protected readonly pickFile = pickFile;")
        if self.route_keys:
            lines += ["", "  protected go(path: string): void {", "    void this.router.navigateByUrl(path);", "  }"]
        if self.methods:
            lines += ["", *self.methods]
        lines += ["}", ""]
        return cls, "\n".join(lines)

    def used(self) -> tuple[set[str], set[str]]:
        """Element and attribute names in the last rendered template (for contract checks)."""
        return tags_and_attributes(self.body)


FORMS_TS = """import type { AbstractControl, FormGroup } from "@angular/forms";

/** The message mat-error shows for an invalid control (rules come from the specification). */
export function errorText(control: AbstractControl | null): string {
  const errors = control?.errors;
  if (!errors) return "";
  if (errors["required"]) return "This field is required.";
  if (errors["min"]) return `Enter ${errors["min"].min} or more.`;
  if (errors["max"]) return `Enter ${errors["max"].max} or less.`;
  if (errors["minlength"]) return `Enter at least ${errors["minlength"].requiredLength} characters.`;
  if (errors["maxlength"]) return `Enter at most ${errors["maxlength"].requiredLength} characters.`;
  if (errors["pattern"]) return "Use the expected format.";
  return "Check this value.";
}

export function invalidLabels(form: FormGroup, labels: Record<string, string>): string[] {
  return Object.entries(form.controls)
    .filter(([, control]) => control.invalid)
    .map(([name]) => labels[name] ?? name);
}

export function fixText(count: number): string {
  return `Fix ${count} field(s)`;
}

export function joinLabels(labels: readonly string[]): string {
  return " " + labels.join(", ");
}

/** File inputs are not part of reactive forms; the chosen file's name is kept per field. */
export function pickFile(files: Record<number, string | null>, index: number, event: Event): void {
  const input = event.target as HTMLInputElement | null;
  files[index] = input?.files?.[0]?.name ?? null;
}
"""

STORE_TS = """import { signal, type Signal, type WritableSignal } from "@angular/core";

export interface Entity {
  id: string;
}

function newId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/** Keeps records in this browser (localStorage when available, otherwise in memory), as a signal. */
export class LocalStore<T extends Entity> {
  private readonly key: string;
  private readonly items: WritableSignal<readonly T[]>;
  readonly list: Signal<readonly T[]>;

  constructor(collection: string) {
    this.key = `generated-app:${collection}`;
    this.items = signal(this.load());
    this.list = this.items.asReadonly();
  }

  create(values: Omit<T, "id">): T {
    const record = { ...values, id: newId() } as T;
    this.commit([...this.items(), record]);
    return record;
  }

  remove(id: string): void {
    this.commit(this.items().filter((r) => r.id !== id));
  }

  private load(): readonly T[] {
    try {
      const saved = window.localStorage.getItem(this.key);
      return saved ? (JSON.parse(saved) as T[]) : [];
    } catch {
      return [];
    }
  }

  private commit(next: readonly T[]): void {
    this.items.set(next);
    try {
      window.localStorage.setItem(this.key, JSON.stringify(next));
    } catch {
      // Storage unavailable (private mode, quota): keep the records in memory.
    }
  }
}
"""

_ENTITY_HELPERS = """
/** Converts form values to a typed record and stores it. */
export function saveRecord(entity: EntityName, values: Record<string, unknown>): void {
  const record: Record<string, string | number | boolean | null> = {};
  for (const [name, kind] of Object.entries(FIELD_KINDS[entity])) {
    const raw = values[name];
    if (kind === "boolean") record[name] = raw === true;
    else if (raw === null || raw === undefined || raw === "") record[name] = null;
    else if (kind === "number") record[name] = Number(raw);
    else record[name] = String(raw);
  }
  (stores[entity] as unknown as LocalStore<Entity>).create(record as Omit<Entity, "id">);
}

/** A short human label for a record: its first non-empty field, or a shortened id. */
export function displayName(entity: string, record: Entity): string {
  const kinds = FIELD_KINDS[entity as EntityName];
  const values = record as unknown as Record<string, unknown>;
  for (const name of Object.keys(kinds ?? {})) {
    const value = values[name];
    if (value !== null && value !== undefined && value !== "") return formatValue(value);
  }
  return record.id.slice(0, 8);
}

export function displayRef(entity: string, id: unknown): string {
  if (typeof id !== "string" || !id) return "—";
  const store = stores[entity as EntityName] as unknown as LocalStore<Entity> | undefined;
  const match = store?.list().find((r) => r.id === id);
  return match ? displayName(entity, match) : id.slice(0, 8);
}

export function formatValue(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "number") return value.toLocaleString();
  return String(value);
}
"""


def entities_ts(spec: ApplicationSpec, header: str) -> str:
    lines = [header.rstrip("\n"), "", 'import { LocalStore, type Entity } from "./store";', ""]
    if not spec.entities:
        lines += [
            "export type { Entity };",
            "// No data entities are specified yet.",
            "export const stores: Record<string, LocalStore<Entity>> = {};",
            "",
        ]
        return "\n".join(lines)
    lines.append("export type { Entity };")
    lines.append("")
    for entity in spec.entities:
        lines.append(f"/** Generated from entity {literal(entity.id)}. */")
        lines.append(f"export interface {type_name(entity.id)} extends Entity {{")
        for field in entity.fields:
            lines.append(f"  {literal(field.name)}: {_ts_type(field.type)}{'' if field.required else ' | null'};")
        lines += ["}", ""]
    lines.append("export const stores = {")
    lines += [f"  {literal(e.id)}: new LocalStore<{type_name(e.id)}>({literal(e.id)})," for e in spec.entities]
    lines += ["};", "", "export type EntityName = keyof typeof stores;", ""]
    kinds = []
    for entity in spec.entities:
        entries = ", ".join(f"{literal(f.name)}: {literal(_kind(f.type))}" for f in entity.fields)
        kinds.append(f"  {literal(entity.id)}: {{ {entries} }},")
    lines += [
        'const FIELD_KINDS: Record<EntityName, Record<string, "string" | "number" | "boolean">> = {',
        *kinds,
        "};",
        _ENTITY_HELPERS,
    ]
    return "\n".join(lines)


STYLES_CSS = """/* Generated styles: Material 3 system variables (--mat-sys-*) with fallbacks. */
html,
body {
  height: 100%;
  margin: 0;
}
body {
  font: var(--mat-sys-body-medium, 400 0.875rem/1.25rem Roboto, "Helvetica Neue", Arial, sans-serif);
  background: var(--mat-sys-surface, #fbf8ff);
  color: var(--mat-sys-on-surface, #1a1b21);
}
.app-header {
  display: flex;
  align-items: center;
  padding: 12px 24px;
  background: var(--mat-sys-surface-container, #eeedf4);
}
.app-title {
  font: var(--mat-sys-title-large, 400 1.375rem/1.75rem Roboto, sans-serif);
}
.app-body {
  display: grid;
  grid-template-columns: 220px minmax(0, 1fr);
  min-height: calc(100% - 56px);
}
@media (max-width: 720px) {
  .app-body {
    grid-template-columns: 1fr;
  }
}
.app-nav ul {
  list-style: none;
  margin: 0;
  padding: 16px 8px;
  display: grid;
  gap: 4px;
}
.app-nav a {
  display: block;
  padding: 8px 16px;
  border-radius: var(--mat-sys-corner-full, 9999px);
  color: var(--mat-sys-on-surface-variant, #44464f);
  text-decoration: none;
}
.app-nav a.active {
  background: var(--mat-sys-secondary-container, #dce2f9);
  color: var(--mat-sys-on-secondary-container, #141b2c);
}
.app-nav a:focus-visible {
  outline: 2px solid var(--mat-sys-primary, #005cbb);
  outline-offset: 2px;
}
main {
  padding: 24px;
  display: grid;
  gap: 16px;
  align-content: start;
  max-width: 960px;
}
h1 {
  font: var(--mat-sys-headline-small, 400 1.5rem/2rem Roboto, sans-serif);
  margin: 0;
}
h2 {
  font: var(--mat-sys-title-large, 400 1.375rem/1.75rem Roboto, sans-serif);
  margin: 0;
}
h3 {
  font: var(--mat-sys-title-medium, 500 1rem/1.5rem Roboto, sans-serif);
  margin: 0;
}
h4 {
  font: var(--mat-sys-title-small, 500 0.875rem/1.25rem Roboto, sans-serif);
  margin: 0;
}
p {
  margin: 0;
}
.subtle {
  font: var(--mat-sys-body-small, 400 0.75rem/1rem Roboto, sans-serif);
  color: var(--mat-sys-on-surface-variant, #44464f);
}
form {
  display: grid;
  gap: 4px;
  max-width: 560px;
}
.actions,
.toolbar {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
.file-field {
  display: grid;
  gap: 4px;
  margin-bottom: 16px;
}
.message {
  padding: 12px 16px;
  border-radius: var(--mat-sys-corner-medium, 12px);
}
.message-info {
  background: var(--mat-sys-secondary-container, #dce2f9);
  color: var(--mat-sys-on-secondary-container, #141b2c);
}
.message-success {
  background: var(--mat-sys-tertiary-container, #fad8fd);
  color: var(--mat-sys-on-tertiary-container, #28132e);
}
.message-warning,
.message-error {
  background: var(--mat-sys-error-container, #ffdad6);
  color: var(--mat-sys-on-error-container, #410002);
}
.stat-value {
  font: var(--mat-sys-headline-small, 400 1.5rem/2rem Roboto, sans-serif);
}
.unsupported {
  padding: 12px 16px;
  border: 1px dashed var(--mat-sys-outline, #757780);
  border-radius: var(--mat-sys-corner-medium, 12px);
}
button.danger {
  --mat-button-filled-container-color: var(--mat-sys-error, #ba1a1a);
  --mat-button-filled-label-text-color: var(--mat-sys-on-error, #ffffff);
}
td.empty {
  padding: 16px;
}
"""


def brand_css(theme: BrandTheme | None) -> str:
    """M3 system-variable overrides for an organization brand theme (empty for the default theme)."""
    if theme is None:
        return ""
    ramp = brand_ramp(theme.brand_color)
    lines = [
        "",
        f"/* Organization brand theme {theme.selector}: overrides of the Material 3 system variables. */",
        ":root {",
        f"  --mat-sys-primary: {ramp[80]};",
        "  --mat-sys-on-primary: #ffffff;",
        f"  --mat-sys-primary-container: {ramp[150]};",
        f"  --mat-sys-on-primary-container: {ramp[20]};",
        f"  --mat-sys-corner-medium: {theme.material_radius};",
        "}",
    ]
    if theme.font_family:
        lines += ["body,", "button,", "input,", "select,", "textarea {", f"  font-family: {theme.font_family};", "}"]
    return "\n".join(lines) + "\n"


def _app_ts(header: str, title: str, links: list[tuple[str, str]]) -> str:
    data = [{"path": "/" + path, "label": label} for path, label in links]
    return "\n".join(
        [
            header.rstrip("\n"),
            "",
            'import { Component } from "@angular/core";',
            'import { RouterLink, RouterLinkActive, RouterOutlet } from "@angular/router";',
            "",
            f"const TITLE = {literal(title)};",
            f"const LINKS = {literal(data)} as const;",
            "",
            "@Component({",
            '  selector: "app-root",',
            "  imports: [RouterLink, RouterLinkActive, RouterOutlet],",
            "  template: `",
            '    <header class="app-header"><span class="app-title">{{ title }}</span></header>',
            '    <div class="app-body">',
            '      <nav class="app-nav" aria-label="Screens">',
            "        <ul>",
            "          @for (link of links; track link.path) {",
            "            <li>",
            '              <a [routerLink]="link.path" routerLinkActive="active" ariaCurrentWhenActive="page">',
            "                {{ link.label }}",
            "              </a>",
            "            </li>",
            "          }",
            "        </ul>",
            "      </nav>",
            "      <main><router-outlet /></main>",
            "    </div>",
            "  `,",
            "})",
            "export class App {",
            "  protected readonly title = TITLE;",
            "  protected readonly links = LINKS;",
            "}",
            "",
        ]
    )


def _routes_ts(header: str, screens: list[tuple[str, str, str]]) -> str:
    lines = [header.rstrip("\n"), "", 'import type { Routes } from "@angular/router";']
    for cls, _, _ in screens:
        lines.append(f"import {{ {cls} }} from {literal('./screens/' + cls_file(cls))};")
    lines += ["", "export const routes: Routes = ["]
    for cls, path, title in screens:
        lines.append(f"  {{ path: {literal(path)}, component: {cls}, title: {literal(title)} }},")
    if screens:
        first = screens[0][1]
        lines.append(f'  {{ path: "", pathMatch: "full", redirectTo: {literal(first)} }},')
        lines.append(f'  {{ path: "**", redirectTo: {literal(first)} }},')
    lines += ["];", ""]
    return "\n".join(lines)


def cls_file(cls: str) -> str:
    """AdjustmentRulesScreen -> adjustment-rules-screen (Angular file naming)."""
    out = []
    for i, ch in enumerate(cls):
        if ch.isupper() and i:
            out.append("-")
        out.append(ch.lower())
    return "".join(out)


def _static_files(name: str, title: str, header: str) -> dict[str, str]:
    tools = toolchain()
    package = {
        "name": name,
        "private": True,
        "version": "0.1.0",
        "engines": {"node": tools["node"]},
        "scripts": {"start": "ng serve", "build": "ng build", "watch": "ng build --watch"},
        "dependencies": tools["dependencies"],
        "devDependencies": tools["devDependencies"],
    }
    angular = {
        "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
        "version": 1,
        "cli": {"analytics": False, "packageManager": "npm"},
        "newProjectRoot": "projects",
        "projects": {
            "app": {
                "projectType": "application",
                "root": "",
                "sourceRoot": "src",
                "prefix": "app",
                "architect": {
                    "build": {
                        "builder": "@angular/build:application",
                        "options": {
                            "browser": "src/main.ts",
                            "index": "src/index.html",
                            "tsConfig": "tsconfig.json",
                            "outputPath": "dist",
                            "styles": ["@angular/material/prebuilt-themes/azure-blue.css", "src/styles.css"],
                        },
                        "configurations": {
                            "production": {
                                "outputHashing": "all",
                                "budgets": [{"type": "initial", "maximumWarning": "1.5mb", "maximumError": "3mb"}],
                            },
                            "development": {"optimization": False, "sourceMap": True},
                        },
                        "defaultConfiguration": "production",
                    },
                    "serve": {
                        "builder": "@angular/build:dev-server",
                        "configurations": {
                            "production": {"buildTarget": "app:build:production"},
                            "development": {"buildTarget": "app:build:development"},
                        },
                        "defaultConfiguration": "development",
                    },
                },
            }
        },
    }
    tsconfig = {
        "compileOnSave": False,
        "compilerOptions": {
            "strict": True,
            "noImplicitOverride": True,
            "noImplicitReturns": True,
            "noFallthroughCasesInSwitch": True,
            "skipLibCheck": True,
            "isolatedModules": True,
            "target": "ES2022",
            "module": "preserve",
            "lib": ["ES2022", "dom"],
            "types": [],
            "outDir": "./out-tsc",
        },
        "angularCompilerOptions": {
            "strictInjectionParameters": True,
            "strictInputAccessModifiers": True,
            "strictTemplates": True,
        },
        "files": ["src/main.ts"],
    }
    safe_title = html.escape(" ".join(title.split()))
    return {
        "package.json": json.dumps(package, indent=2) + "\n",
        "angular.json": json.dumps(angular, indent=2) + "\n",
        "tsconfig.json": json.dumps(tsconfig, indent=2) + "\n",
        ".gitignore": "node_modules/\ndist/\n.angular/\nout-tsc/\n",
        "src/index.html": (
            '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n'
            f"    <title>{safe_title}</title>\n"
            '    <base href="/" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n'
            "  </head>\n  <body>\n    <app-root></app-root>\n  </body>\n</html>\n"
        ),
        "src/main.ts": header
        + "\n"
        + 'import { provideZonelessChangeDetection } from "@angular/core";\n'
        + 'import { bootstrapApplication } from "@angular/platform-browser";\n'
        + 'import { provideRouter } from "@angular/router";\n'
        + 'import { App } from "./app/app";\n'
        + 'import { routes } from "./app/app.routes";\n\n'
        + "bootstrapApplication(App, {\n"
        + "  providers: [provideZonelessChangeDetection(), provideRouter(routes)],\n"
        + "}).catch((error: unknown) => console.error(error));\n",
        "src/styles.css": STYLES_CSS,
    }


def _readme(
    title: str, spec_revision: int | None, contract: DesignSystemContract, screens: list[tuple[str, str, str]]
) -> str:
    rows = "\n".join(f"| {html.escape(t)} | `/{p}` |" for _, p, t in screens) or "| (none yet) | |"
    return (
        f"# {html.escape(title)}\n\n"
        f"Generated by `{GENERATOR}@{GENERATOR_VERSION}` from specification revision "
        f"{spec_revision if spec_revision is not None else '(unsaved)'}, UI IR v1, design system "
        f"{contract.name} (`{contract.library.package}@{contract.library.version}`).\n\n"
        "```bash\nnpm ci\nnpm start      # http://localhost:4200\nnpm run build  # dist/browser\n```\n\n"
        "| Screen | Route |\n|---|---|\n"
        f"{rows}\n\n"
        "Records are kept in the browser (localStorage). Edit and delete row actions and an HTTP data store "
        "are generated for React projects so far, not yet for Angular.\n"
    )


def _list_routes(document: UiDocument) -> dict[str, str]:
    out: dict[str, str] = {}
    for screen in document.screens:
        for node in screen.body:
            if isinstance(node, Table) and node.entity_id and node.entity_id not in out:
                out[node.entity_id] = screen.route
    return out


def generate_project(
    spec: ApplicationSpec,
    contract: DesignSystemContract,
    *,
    spec_revision: int | None = None,
    document: UiDocument | None = None,
    theme: BrandTheme | None = None,
) -> GeneratedProject:
    if contract.framework != "angular":
        raise GenerationError(f"{contract.name} is not an Angular design system")
    document = document or derive_document(spec, spec_revision=spec_revision)
    issues = validate_document(document, spec)
    errors = [i for i in issues if i.severity == "error"]
    if errors:
        raise GenerationBlocked(errors)
    header = _header(spec_revision, contract)
    title = spec.metadata.name
    routes = {s.id: s.route for s in document.screens}
    list_routes = _list_routes(document)
    files: dict[str, str] = {}
    files.update(_static_files(package_name(title), title, header))
    files["src/styles.css"] += brand_css(theme)
    files["src/app/forms.ts"] = header + "\n" + FORMS_TS
    files["src/app/data/store.ts"] = header + "\n" + STORE_TS
    files["src/app/data/entities.ts"] = entities_ts(spec, header)
    warnings = [i for i in issues if i.severity == "warning"]
    registered: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for index, screen in enumerate(document.screens):
        builder = ScreenBuilder(screen, index, spec, list_routes, routes)
        cls, source = builder.file(header)
        if cls in seen:
            raise GenerationError(f"two screens map to the class name {cls}")
        seen.add(cls)
        files[f"src/app/screens/{cls_file(cls)}.ts"] = source
        registered.append((cls, screen.route.lstrip("/"), screen.title))
        warnings += builder.warnings
    files["src/app/app.ts"] = _app_ts(header, title, [(p, t) for _, p, t in registered])
    files["src/app/app.routes.ts"] = _routes_ts(header, registered)
    files["README.md"] = _readme(title, spec_revision, contract, registered)
    project = GeneratedProject(
        generator=f"{GENERATOR}@{GENERATOR_VERSION}",
        spec_revision=spec_revision,
        design_system=design_system_label(contract, theme),
        files=dict(sorted(files.items())),
        warnings=warnings,
    )
    manifest = {
        "generator": project.generator,
        "spec_revision": spec_revision,
        "ui_ir_version": document.ir_version,
        "design_system": project.design_system,
        "library": f"{contract.library.package}@{contract.library.version}",
        "files": {path: project.sha256(path) for path in project.files},
    }
    project.files[MANIFEST] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    project.files = dict(sorted(project.files.items()))
    return project
